#!/usr/bin/expect -f       
        set timeout 20
	set IPaddress [lindex $argv 0]
	set Username "slork"
	set Password "hoagie"
	set Directory "logs/"

	spawn ssh -o "StrictHostKeyChecking no" $Username@$IPaddress svn up slork/groups/2012/mayank-jiffer-hunter
	expect "*assword:"
	send "$Password\r"
	interact
exit
