var DISQUS=function(b){var e={AssertionError:function(d){this.message=d}};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(d,a){if(!d)throw new e.AssertionError(a);};var d=[];e.define=function(i,a){typeof i==="function"&&(a=i,i="");for(var j=i.split("."),f=j.shift(),h=e,q=(a||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},b);f;)h=h[f]?h[f]:h[f]={},f=j.shift();for(var k in q)q.hasOwnProperty(k)&&
(q.__overwrites__||h[k]!==null&&e.assert(!h.hasOwnProperty(k),"Unsafe attempt to redefine existing module with "+k),h[k]=q[k],d.push(function(a,f){return function(){delete a[f]}}(h,k)));return h};e.use=function(d){return e.define(d)};e.cleanup=function(){for(var b=0;b<d.length;b++)d[b]()};return e}(this);
DISQUS.define(function(b,e){var d=b.document,i=d.getElementsByTagName("head")[0]||d.body,a={running:!1,timer:null,queue:[]};DISQUS.defer=function(d,f){function h(){var f=a.queue;if(f.length===0)a.running=!1,clearInterval(a.timer);for(var h=0,d;d=f[h];h++)d[0]()&&(f.splice(h--,1),d[1]())}a.queue.push([d,f]);h();if(!a.running)a.running=!0,a.timer=setInterval(h,100)};DISQUS.each=function(a,f){var h=a.length,d=Array.prototype.forEach;if(isNaN(h))for(var b in a)a.hasOwnProperty(b)&&f(a[b],b,a);else if(d)d.call(a,
f);else for(d=0;d<h;d++)f(a[d],d,a)};DISQUS.serializeArgs=function(a){var f=[];DISQUS.each(a,function(a,d){a!==e&&f.push(d+(a!==null?"="+encodeURIComponent(a):""))});return f.join("&")};DISQUS.serialize=function(a,f,d){f&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=DISQUS.serializeArgs(f));if(d)return f={},f[(new Date).getTime()]=null,DISQUS.serialize(a,f);f=a.length;return a.charAt(f-1)=="&"?a.slice(0,f-1):a};DISQUS.require=function(a,f,h,b,e){function l(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))b&&
b(),n&&clearTimeout(n),DISQUS.bean.remove(a.target,o,l)}var m=d.createElement("script"),o=m.addEventListener?"load":"readystatechange",n=null;m.src=DISQUS.serialize(a,f,h);m.async=!0;m.charset="UTF-8";(b||e)&&DISQUS.bean.add(m,o,l);e&&(n=setTimeout(function(){e()},2E4));i.appendChild(m);return DISQUS};DISQUS.requireStylesheet=function(a,f,h){var b=d.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=DISQUS.serialize(a,f,h);i.appendChild(b);return DISQUS};DISQUS.requireSet=function(a,
f,d){var b=a.length;DISQUS.each(a,function(a){DISQUS.require(a,{},f,function(){--b===0&&d()})})};DISQUS.injectCss=function(a){var f=d.createElement("style");f.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");b.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));f.styleSheet?f.styleSheet.cssText=a:f.appendChild(d.createTextNode(a));i.appendChild(f)}});
DISQUS.define("JSON",function(){function b(a){return a<10?"0"+a:a}function e(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var d=k[a];return typeof d==="string"?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(f,b){var p,i,v,w,y=h,s,j=b[f];j&&typeof j==="object"&&typeof j.toJSON==="function"&&!a&&(j=j.toJSON(f));typeof l==="function"&&(j=l.call(b,f,j));switch(typeof j){case "string":return e(j);case "number":return isFinite(j)?String(j):"null";case "boolean":case "null":return String(j);
case "object":if(!j)return"null";h+=q;s=[];if(Object.prototype.toString.apply(j)==="[object Array]"){w=j.length;for(p=0;p<w;p+=1)s[p]=d(p,j)||"null";v=s.length===0?"[]":h?"[\n"+h+s.join(",\n"+h)+"\n"+y+"]":"["+s.join(",")+"]";h=y;return v}if(l&&typeof l==="object"){w=l.length;for(p=0;p<w;p+=1)i=l[p],typeof i==="string"&&(v=d(i,j))&&s.push(e(i)+(h?": ":":")+v)}else for(i in j)Object.hasOwnProperty.call(j,i)&&(v=d(i,j))&&s.push(e(i)+(h?": ":":")+v);v=s.length===0?"{}":h?"{\n"+h+s.join(",\n"+h)+"\n"+
y+"}":"{"+s.join(",")+"}";h=y;return v}}var i={},a=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var j=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,q,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;i.stringify=function(a,f,p){var b;q=h="";if(typeof p==="number")for(b=0;b<p;b+=1)q+=" ";else typeof p==="string"&&(q=p);if((l=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return d("",{"":a})};i.parse=function(a,f){function d(a,
w){var b,h,e=a[w];if(e&&typeof e==="object")for(b in e)Object.hasOwnProperty.call(e,b)&&(h=d(e,b),h!==void 0?e[b]=h:delete e[b]);return f.call(a,w,e)}var b,a=String(a);j.lastIndex=0;j.test(a)&&(a=a.replace(j,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),
typeof f==="function"?d({"":b},""):b;throw new SyntaxError("JSON.parse");};var m={a:[1,2,3]},o,n;if(Object.toJSON&&Object.toJSON(m).replace(/\s/g,"")==='{"a":[1,2,3]}')o=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(m='{"a":[1,2,3]}'.evalJSON(),m.a&&m.a.length===3&&m.a[2]===3&&(n=function(a){return a.evalJSON()}));(function(){var f=[1,2,3];typeof f.toJSON==="function"&&(f=f.toJSON(),a=!(f&&f.length===3&&f[2]===3))})();if(a||!o||!n)return{stringify:i.stringify,parse:i.parse};return{stringify:o,
parse:n}});
DISQUS.define("Bus",function(){function b(a){a=a.split("/");return a[0]+"//"+a[2]}var e=DISQUS.use("JSON"),d=window.location.hash.slice(1),i=window.parent,a=document.referrer,j={};j.client=b(document.location.href);j.host=a?b(a):j.client;return{origins:j,postMessage:function(a){a.sender=d;a=e.stringify(a);i.postMessage(a,j.host)},sendHostMessage:function(a,d){d=d||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:d})},sendGlobalMessage:function(a,d){d=d||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:d})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var b=window.addEventListener?window.addEventListener:window.attachEvent,e=window.addEventListener?"message":"onmessage";if(!b)throw Error("No event support.");b(e,function(d){var b=DISQUS.Bus,a=d.origin;if(!(a!=b.origins.client&&a!=b.origins.host)){var e;try{e=DISQUS.JSON.parse(d.data)}catch(f){return}d=e.data;switch(e.scope){case "client":b.trigger(d.eventName,d.data)}}},!1)});
DISQUS.define(function(b){var b=b.document,e=require("bean"),d=_.extend,i=navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i),a;try{localStorage.setItem("_test","_test"),localStorage.removeItem("_test"),a=!0}catch(j){a=!1}var f={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:e,extend:d,debug:!1,browser:{mobile:i,localStorage:a,contentEditable:"isContentEditable"in b.documentElement},addBlocks:function(){return function(a){a(DISQUS)}}};
f.templateGlobals={urls:DISQUS.use("urls"),sso:null,_:{pluralize:_.pluralize}};f.renderBlock=function(a,d){return DISQUS.blocks[a](f.templateGlobals,d)};f.assureOffset=function(a){return a.indexOf("+")>=0?a:a+"+00:00"};a=f.Builder=function(){this.accum=[]};_.extend(a.prototype,{put:function(a){this.accum.push(a)},esc:function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});
return f});
DISQUS.define("urls",function(){return{media:"http://mediacdn.disqus.com/1339189988",root:"http://disqus.com",realertime:"http://realtime.services.disqus.com",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+encodeURIComponent(document.referrer),help:"http://disqus.com/help/",editProfile:"http://disqus.com/account/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",
facebook:"http://disqus.com/_ax/facebook/begin/"},loading:"http://mediacdn.disqus.com/1339189988/html/simple-loading.html",avatar:{generic:"http://mediacdn.disqus.com/1339189988/images/noavatar92.png"}}});
DISQUS.define("api",function(){function b(d){function a(f){var m=f.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,m.length)===m&&(f=DISQUS.JSON.parse(f.originalEvent.data),f.requestId==b&&(m=f.code===0?d.success:d.error,delete f.requestId,(m||function(){})(f),document.body.removeChild(k),document.body.removeChild(e),$(window).unbind("message",a)))}var b=_.uniqueId(),f=document.createElement("div"),e=document.createElement("form"),q="frame_"+b,k;f.innerHTML='<iframe name="'+q+'"></iframe>';k=f.childNodes[0];
e.target=q;e.action=d.url.replace(".json",".pm");e.method=d.method||"GET";d.data=_.extend(d.data,{callback:b,referrer:document.referrer});_.each(d.data,function(a,d){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var f=document.createElement("input");f.type="hidden";f.name=d;f.value=a;e.appendChild(f)})});$(window).bind("message",a);document.body.appendChild(k);document.body.appendChild(e);e.submit()}function e(b){b=_.defaults(b,d);b.data=b.data||{};b.data.api_key=
DISQUS.apiKey;$.ajax(b)}var d={};return{defaults:function(b){_.extend(d,b)},ajax:e,call:function(d,a){a=a||{};a.url=(a.secure?DISQUS.urls.apiSecure:DISQUS.urls.api)+d;a.data=_.extend(a.data||{},{api_key:DISQUS.apiKey});(a.secure?b:e)(a)}}});(function(b){b.ajax=function(b){b.method=b.type;b.type=b.dataType;delete b.dataType;return DISQUS.api.ajax(b)};b.Collection.prototype.parse=function(b){return b.response}})(Backbone);
DISQUS.define("cookies",function(){return{create:function(b,e,d){b=b+"="+e+"; path=/";d.domain&&(b+="; domain=."+d.domain);d.expiresIn&&(e=new Date,e.setTime(e.getTime()+d.expiresIn),b+="; expires="+e.toGMTString());document.cookie=b},read:function(b){b+="=";for(var e=document.cookie.split(";"),d,i=0;i<e.length;i++){for(d=e[i];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(b)===0)return d.substring(b.length,d.length)}return null},erase:function(b,e){var d=new Date;d.setTime(d.getTime()+
-864E5);d=b+"=; path=/;expires="+d.toGMTString();e.domain&&(d+="; domain=."+e.domain);document.cookie=d}}});
DISQUS.define("lounge.utils",function(){function b(a){function d(a){a=Number(a).toString(16);return a.length==1?"0"+a:a}if(a.substr(0,1)==="#")return a;var b=/.*?rgb\((\d+),\s*(\d+),\s*(\d+)\)/.exec(a);if(!b||b.length!==4)return"";var a=d(b[1]),e=d(b[2]),b=d(b[3]);return"#"+a+e+b}var e=RegExp("[\\u0021-\\u002F\\u003A-\\u0040\\u005B-\\u0060\\u007B-\\u007E\\u00A1-\\u00BF\\u2010-\\u2027\\u2030-\\u205E\\u2300-\\u23FF\\u2E00-\\u2E7F\\u3001-\\u303F\\uFE10-\\uFE19\\uFE30-\\uFE4F\\uFE50-\\uFE6B\\uFF01-\\uFF0F\\uFF1A-\\uFF20\\uFF3B-\\uFF40\\uFF5B-\\uFF60\\uFF5F-\\uFF64]+$"),d=
{domain:DISQUS.urls.root.split("/")[2],create:function(a,b){DISQUS.cookies.create(a,b,{domain:d.domain,expiresIn:31536E6})},read:DISQUS.cookies.read,erase:function(a){DISQUS.cookies.erase(a,{domain:d.domain})}},i=/^[a-z0-9_.%+\-]+@[0-9a-z.\-]+\.[a-z.]{2,6}$/i;return{attempt:function(a,d){try{_.bind(a,d||{})()}catch(b){return b}return null},extract:function(a,d){for(var b=d.split("."),e=b.shift();e;){if(b.length===0)return a[e];if(!_.isObject(a[e]))return;a=a[e];e=b.shift()}return a},addStylesheetRules:function(a){function d(){var e=
_.find(document.styleSheets,function(a){return(a.ownerNode||a.owningElement).id===b});if(!e)return void setTimeout(d,50);for(var h=0,i=a.length;h<i;h++){var m=1,o=a[h],n=o[0],r="";Object.prototype.toString.call(o[1][0])==="[object Array]"&&(o=o[1],m=0);for(var u=o.length;m<u;m++){var p=o[m];r+=p[0]+":"+p[1]+(p[2]?" !important":"")+";\n"}e.insertRule?e.insertRule(n+"{"+r+"}",e.cssRules.length):e.addRule(n,r,-1)}}var b="css_"+(new Date).getTime(),e=document.createElement("style");e.id=b;document.getElementsByTagName("head")[0].appendChild(e);
window.createPopup||e.appendChild(document.createTextNode(""));d()},escapeColor:function(a){return b(a).replace(/[^#A-Fa-f0-9]/g,"")},makeCORSRequest:function(a,d,b){b=b||function(){};if(typeof XMLHttpRequest=="undefined")return null;var e=new XMLHttpRequest;if("withCredentials"in e)e.open(a,d,!0),e.onreadystatechange=b;else if(typeof XDomainRequest!="undefined"){if(a!=="GET"&&a!=="POST")return null;e=new XDomainRequest;e.open(a,d);e.onload=b}else e=null;return e},hashStorage:function(){var a={};
return{getItem:function(b){return a.hasOwnProperty(b)?a[b]:null},setItem:function(b,d){a[b]=String(d)},removeItem:function(b){delete a[b]}}}(),cookies:d,niceTruncate:function(a,b){if(a.length<=b)return a;var d=a=a.slice(0,b-1),h=/(^.*\S)\s/.exec(a);h&&(a=h[1]);(h=e.exec(a))&&(a=a.slice(0,a.length-h[0].length));a.length<0.5*d.length&&(a=d);return a+"\u2026"},isWindowClosed:function(a){if(!a)return!0;try{return a.closed||a.closed===void 0}catch(b){return!0}},validateEmail:function(a){return i.test(a)}}});
DISQUS.define("lounge.realtime",function(){function b(b){this.url=b+"?"+ +new Date;this.xhr=null;this.len=0}var e=DISQUS.use("lounge.utils");_.extend(b.prototype,Backbone.Events,{onLoad:function(){var b=this.xhr;b.readyState!==void 0&&b.readyState!=4||b.status!==void 0&&b.status!==200||this.trigger("success")},onError:function(){this.trigger("error")},onProgress:function(){var b=this,e=b.xhr.responseText,a=0;e&&b.len!==e.length&&(_.each(e.slice(b.len).split("\n"),function(e){a+=e.length+1;try{e=JSON.parse(e)}catch(f){a-=
e.length+1;return}b.trigger("progress",e)}),b.len+=a)},run:function(){var b=this;b.xhr=e.makeCORSRequest("GET",b.url,function(){b.onLoad()});b.xhr.onerror=function(){b.onError()};b.xhr.onprogress=function(){b.onProgress()};try{b.xhr.send()}catch(i){DISQUS.log("Attempt to send a CORS request failed.")}}});return{Firehose:b}});
DISQUS.define("lounge.models",function(){var b=DISQUS.use("lounge.collections"),e=DISQUS.use("lounge.utils"),d=DISQUS.use("Bus"),i=Backbone.Model.extend({defaults:{settings:{}}}),a=Backbone.Model.extend({defaults:{author:null,category:null,createdAt:null,forum:null,identifiers:[],ipAddress:null,isClosed:!1,isDeleted:!1,hasStreaming:!1,link:null,message:null,slug:null,title:null,userSubscription:!1,posts:0,reactions:0,likes:0,dislikes:0,userScore:0},initialize:function(a,d){var e=this,d=d||{};e.moderators=
d.moderators;e.forum=d.forum;e.users=d.users||new b.UserCollection;e.posts=new b.PostCollection(d.posts,{thread:e,cursor:d.postCursor});e.reactions=new b.ReactionsCollection(null,{thread:e});e.votes=new b.ThreadVoteCollection;e.posts.bind("add reset",function(a){a=a.models?a.models:[a];_.each(a,function(a){e.users.get(a.author.id)||e.users.add(a.author)})});e.posts.bind("destroy",function(){e.set("posts",e.get("posts")-1)});e.bind("change:posts",e.broadcastPostCount,e);e.queue=new b.QueuedPostCollection(null,
{thread:e})},_vote:function(a,b){var d=a-b;if(d===0)return d;this.set("likes",this.get("likes")+d);return d},vote:function(a){var b=this;b._vote(a,b.get("userScore"))!==0&&(this.set("userScore",a),DISQUS.api.call("threads/vote.json",{data:{thread:this.id,vote:a},method:"POST",success:function(d){d.response.id&&(b.votes.get(d.response.id)||b.votes.add({id:d.response.id,score:a}))}}))},broadcastPostCount:function(){d.sendGlobalMessage("lounge.updateCounter",{count:this.get("posts")})},fetch:function(a){var b=
this,d=b.attributes,a=a||{};DISQUS.api.call("threads/details.json",{data:{thread:d.identifier?"ident:"+d.identifier:"link:"+d.url,forum:d.forum},success:function(d){b.set(d.response);a.success&&a.success()},error:function(){DISQUS.debug?b.save({},{success:a.success}):console.log("Couldn't find thread; not creating in production.")}})},close:function(){this.set("isClosed",!0);DISQUS.api.call("threads/close",{method:"POST",data:{thread:this.id}})},open:function(){this.set("isClosed",!1);DISQUS.api.call("threads/open",
{method:"POST",data:{thread:this.id}})},sync:function(){var a=this,b=a.attributes;DISQUS.api.call("threads/create.json",{data:{title:b.title,forum:b.forum,identifier:b.identifier,url:b.url},method:"POST",success:function(b){a.set(b.response)}})},incrementPostCount:function(a){this.set("posts",this.get("posts")+a)},isModerator:function(a){if(this.moderators)return a=a instanceof m||_.isObject(a)?a.id:a,a=parseInt(a,10),_(this.moderators).contains(a)},subscribe:function(a,b){var a=a!==!1,d=this.get("userSubscription");
if(d!=a){a?this.set("userSubscription",b||!0):this.set("userSubscription",!1);var e={thread:this.id};if(b)e.email=b;else if(!a&&typeof d==="string")e.email=d;DISQUS.api.call("threads/"+(a?"subscribe.json":"unsubscribe.json"),{data:e,method:"POST"})}}}),j=a.extend({defaults:_.extend({postsInInterval:0,topPost:null},a.prototype.defaults)}),f=Backbone.Model.extend({defaults:function(){return{createdAt:moment().format(DISQUS.ISO_8601),dislikes:0,isApproved:!0,isDeleted:!1,isEdited:!1,isFlagged:!1,isHighlighted:!1,
isRealtime:!1,isImmediateReply:!1,isMinimized:null,message:null,raw_message:null,likes:0,media:[],points:0,depth:0,userScore:0}},initialize:function(){this.votes=new b.VoteCollection;this.usersTyping=new b.TypingUserCollection},set:function(a,b,d){if(a&&typeof a!=="string"&&a.author)this.author=new m(a.author),delete a.author;return Backbone.Model.prototype.set.call(this,a,b,d)},messageText:function(){var a=this.get("message");return _.strip(a)},getRelativeCreatedAt:function(){var a=this.get("createdAt");
if(a)return a=DISQUS.assureOffset(a),moment(a,DISQUS.ISO_8601).fromNow()},toJSON:function(){var a=Backbone.Model.prototype.toJSON.call(this);a.isMinimized=this.get("isMinimized")===!1?!1:!this.get("isApproved");if(this.author)a.author=this.author.toJSON();a.relativeCreatedAt=this.getRelativeCreatedAt();return a},validate:function(a){if(!this.id&&!a.id){if(_.isString(a.raw_message)){if(a.raw_message==="")return"Comments can't be blank.";if(a.raw_message.length<2)return"Comments must have at least 2 characters."}if(a.author_email===
""&&a.author_name==="")return"Please sign in or enter a name and email address.";else if(a.author_email===""||a.author_name==="")return"Please enter both a name and email address.";if(_.isString(a.author_email)&&!e.validateEmail(a.author_email))return"Invalid email address format."}},report:function(){this.set("isFlagged",!0);DISQUS.api.call("posts/report.json",{data:{post:this.id},method:"POST"})},_vote:function(a,b){function d(a){f.set("likes",f.get("likes")+a)}function e(a){f.set("dislikes",f.get("dislikes")+
a)}var f=this,p=a-b;if(p===0)return p;f.set("points",f.get("points")+p);a>0?(d(a),e(b)):a<0?(e(-a),d(-b)):b>0?d(-b):e(b);return p},vote:function(a){var b=this;b._vote(a,b.get("userScore"))!==0&&(b.set("userScore",a),DISQUS.api.call("posts/vote.json",{data:{post:b.id,vote:a},method:"POST",success:function(a){b.votes.add({id:a.response.id})}}))},_delete:function(){this.set({isApproved:!1,isDeleted:!0});DISQUS.api.call("posts/remove.json",{data:{post:this.id},method:"POST"})},spam:function(){this.set({isApproved:!1,
isDeleted:!0,isSpam:!0});this.trigger("spam");DISQUS.api.call("posts/spam.json",{data:{post:this.id},method:"POST"})},_create:function(a,b){var d=this,e=a.attributes,f={thread:e.thread,message:e.raw_message};if(e.recaptcha_challenge_field)f.recaptcha_challenge_field=e.recaptcha_challenge_field,f.recaptcha_response_field=e.recaptcha_response_field;if(e.parent)f.parent=e.parent;if(e.author_name)f.author_name=e.author_name,f.author_email=e.author_email;DISQUS.api.call("posts/create.json",{data:f,method:"POST",
success:function(a){d.set(a.response);b.success&&b.success()},error:function(a){b.error&&b.error(JSON.parse(a.response))}})},_update:function(a,b){var d=this,e=a.attributes;DISQUS.api.call("posts/update.json",{data:{post:e.id,message:e.raw_message},method:"POST",success:function(a){d.set(a.response);b.success&&b.success()},error:function(a){b.error&&b.error(JSON.parse(a.response))}})},_read:function(a,b){var d=this,b=b||{};DISQUS.api.call("posts/details.json",{data:{post:d.id},method:"GET",success:function(a){d.set(a.response);
b.success&&b.success()},error:function(a){b.error&&b.error(JSON.parse(a.response))}})},sync:function(a,b,d){d=d||{};switch(a){case "create":this._create(b,d);break;case "update":this._update(b,d);break;case "delete":this._delete();break;case "read":this._read()}}}),h=Backbone.Model.extend({defaults:{userId:null,message:null,parentId:null,immedReply:!1},initialize:function(){this.set("createdAt",moment().format(DISQUS.ISO_8601))},getVisibleParent:function(a){for(var b=this,d;b.get("parentId");){if(d=
a.posts.get(b.get("parentId")))return d;b=a.queue.get(b.get("parentId"));if(!b)break}return null},toPost:function(a){var b=a.posts.get(this.get("parentId")),b=b?b.get("depth")+1:0,b=new f({id:this.id,thread:a.id,message:this.get("message"),parent:this.get("parentId"),depth:b,createdAt:this.get("createdAt"),isRealtime:!0,isImmediateReply:this.get("immedReply")});b.author=a.users.get(this.get("userId"));return b}}),q=Backbone.Model.extend({defaults:{typing:!0},initialize:function(){this.createdAt=moment()}}),
k=Backbone.Model.extend({defaults:{about:null,avatar:{cache:"http://mediacdn.disqus.com/1339189988/images/noavatar92.png",permalink:"http://mediacdn.disqus.com/1339189988/images/noavatar92.png"},connections:{},email:null,emailHash:null,isAnonymous:!0,isFollowedBy:!1,isFollowing:!1,joinedAt:null,name:null,profileUrl:null,url:null,username:null,numPosts:null,numFollowing:null,numFollowers:null,numLikesReceived:null,thread:{canReply:!0}}}),l=k.extend({idAttribute:"emailHash"}),m=k.extend({fetchSession:function(a){var b=
this,a=a||{},d={thread:a.thread.id,post:a.thread.posts.pluck("id")};d["_"+(new Date).getTime()]=1;DISQUS.api.call("embed/threadDetails.json",{data:d,success:function(d){var d=d.response,e={};d.user&&_.extend(e,d.user,{thread:d.thread,votes:d.votes});b.set(e);b.id&&(a.thread.users.get(b.id)&&a.thread.users.remove(b.id),a.thread.users.add(b));a.success&&a.success(d);a.complete&&a.complete(d)},error:function(b){a.error&&a.error(b);a.complete&&a.complete(b)}})},fetch:function(a){var b=this,a=a||{};DISQUS.api.call("users/details.json",
{data:b.id?{user:b.id}:{},success:function(d){d=d.response;b.set(d);a.success&&a.success(d);a.complete&&a.complete(d)},error:function(b){a.error&&a.error(b);a.complete&&a.complete(b)}})},register:function(a,b){var d=this;DISQUS.api.call("internal/users/register.json",{secure:!0,data:{display_name:a.name,email:a.email},method:"POST",success:function(a){d.set(a.response)},error:b.error||function(){}})},logout:function(){var a=this;DISQUS.api.call("internal/users/logout.json",{method:"POST",success:function(){a.clear({silent:!0});
a.set((new m).attributes);a.unset("id")}})},follow:function(){var a=this;DISQUS.api.call("users/follow.json",{data:{target:this.id},method:"POST",success:function(){a.set("isFollowing",!0)}})},unfollow:function(){var a=this;DISQUS.api.call("users/unfollow.json",{data:{target:this.id},method:"POST",success:function(){a.set("isFollowing",!1)}})}}),k=m.extend({defaults:_.extend({numPosts:0},m.prototype.defaults)}),o=Backbone.Model.extend({defaults:{score:0}}),n=Backbone.Model.extend({defaults:{score:0}}),
r=Backbone.Model.extend({defaults:function(){return{object:{},type:"",createdAt:moment().format(DISQUS.ISO_8601)}},toJSON:function(){var a=Backbone.Model.prototype.toJSON.call(this),b=DISQUS.assureOffset(this.get("createdAt"));a.relativeCreatedAt=moment(b,DISQUS.ISO_8601).fromNow();return a}}),u=Backbone.Model.extend({defaults:function(){return{sender:"",timestamp:moment().valueOf(),type:0,formatted:"",theme:""}}}),p=Backbone.Model.extend({defaults:{enabled:!1}}),A=Backbone.Model.extend({defaults:{thread:null,
forum:null,body:null,service:{url:null,name:null},url:null,title:null},set:function(a,b){if(a&&typeof a!=="string"){if(a.author)this.author=a.author.id?new m(a.author):new l(a.author),delete a.author;if(a.createdAt)a.relativeCreatedAt=moment(DISQUS.assureOffset(a.createdAt),DISQUS.ISO_8601).fromNow()}return Backbone.Model.prototype.set.call(this,a,b)},toJSON:function(){var a=Backbone.Model.prototype.toJSON.call(this);if(this.author)a.author=this.author.toJSON();return a},destroy:function(){DISQUS.api.call("reactions/remove.json",
{data:{reaction:this.id,forum:this.get("forum")},method:"POST"})}});return{Forum:i,Thread:a,TopThread:j,Post:f,QueuedPost:h,Reaction:A,TypingUser:q,User:m,TopUser:k,Vote:o,ThreadVote:n,Notification:u,ActivityItem:r,Switch:p}});
DISQUS.define("lounge.collections",function(){var b=DISQUS.use("lounge.models"),e=DISQUS.use("lounge.utils"),d=Backbone.Collection.extend({model:b.ThreadVote}),i=Backbone.Collection.extend({model:b.User}),a=Backbone.Collection.extend({model:b.Notification,url:DISQUS.urls.api+"messagesx/unread",initialize:function(a,b){this.user=b.user},fetch:function(){Backbone.Collection.prototype.fetch.call(this,{data:{user:"username:"+this.user.get("username")}})},markRead:function(){var a=this,b=_.pluck(a.models,
"id");DISQUS.api.call("messagesx/markRead.json",{data:{messages:b},method:"POST",success:function(){a.remove(b)}})},parse:function(a){return a.response.messages}}),j=Backbone.Collection.extend({model:b.Vote}),f=Backbone.Collection.extend({initialize:function(a,b){this.cursor=b.cursor||{}},fetch:function(a){a.data=_.extend({},a.data||{},{cursor:a.cursor||""});return Backbone.Collection.prototype.fetch.call(this,a)},more:function(a){this.cursor.hasNext?this.fetch(_.extend(a||{},{add:!0,cursor:this.cursor.next})):
a.error&&a.error()},parse:function(a){this.cursor=a.cursor;return Backbone.Collection.prototype.parse.call(this,a)}}),h=f.extend({model:b.Post,url:DISQUS.urls.api+"threads/listPostsThreaded",initialize:function(a,b){f.prototype.initialize.apply(this,arguments);this.thread=b.thread;this.order=e.cookies.read("disqus.order")||"popular"},fetch:function(a){a=a||{};this.order==="popular"?e.cookies.erase("disqus.order"):e.cookies.create("disqus.order",this.order);a=_.extend(a,{data:{limit:h.PAGINATION_LIMIT,
thread:this.thread.id,forum:this.thread.get("forum"),order:this.order}});return f.prototype.fetch.call(this,a)},add:function(a,b){_.isArray(a)||(a=[a]);for(var d=[],e=0;e<a.length;e++)this.get(a[e].id)||d.push(a[e]);Backbone.Collection.prototype.add.call(this,d,b)}},{PAGINATION_LIMIT:50}),q=Backbone.Collection.extend({model:b.QueuedPost,initialize:function(a,b){var d=this;d.thread=b.thread;d.counters={comments:0,replies:{}};d.bind("add",function(a){var b=a.getVisibleParent(d.thread);b?(d.counters.replies[b.id]?
d.counters.replies[b.id]+=1:d.counters.replies[b.id]=1,b.id==a.get("parentId")&&a.set("immedReply",!0)):d.counters.comments+=1})},comparator:function(a){return parseInt(a.get("id"),10)},isDescendant:function(a,b){var c;var d=a.get("parentId"),d=d?this.get(d):null,e={};for(_.each(b,function(a){e[a]=!0});d;){if(e[d.get("id")]===!0)return!0;c=(d=d.get("parentId"))?this.get(d):null,d=c}return!1},drain:function(a){function b(a){var d=[];e.each(function(a){a.get("parentId")===null&&d.push(a.get("id"))});
e.reset(e.filter(function(b){if(b.get("parentId")!==null&&!e.isDescendant(b,d))return b;a(b)}));e.counters.comments=0}function d(b){var f=[],h=[],h=e.filter(function(b){var d=b.getVisibleParent(e.thread);if(!d||d.get("id")!=a)return b;f.push(b)}),f=_.sortBy(f,function(a){return parseInt(a.get("id"),10)});_.each(f,function(a){b(a)});e.reset(h);e.counters.replies[a]=0}var e=this;return(a?d:b)(function(a){e.thread.posts.add(a.toPost(e.thread))})}}),k=Backbone.Collection.extend({model:b.Switch,parse:function(a){return _.map(a,
function(a,b){return{id:b,enabled:a}})},enabled:function(a){return(a=this.get(a))?a.get("enabled"):!1}}),l=Backbone.Collection.extend({models:b.TypingUser,initialize:function(){var a=this;a.gc=null;a.bind("add remove reset",function(){var b=a.count();if(b>0&&a.gc===null)a.gc=setInterval(_.bind(a.cleanup,a),6E4);else if(b<=0&&a.gc!==null)clearInterval(a.gc),a.gc=null},a)},count:function(){var a=0;this.each(function(b){a+=b.get("typing")?1:-1});return a},cleanup:function(){var a=moment();this.reset(this.filter(function(b){return b.createdAt.diff(a,
"minutes")>5}))}}),m=Backbone.Collection.extend({model:b.ActivityItem,url:DISQUS.urls.api+"users/listActivity",initialize:function(a,b){this.user=b.user;this.include=b.include||null},fetch:function(){var a={user:"username:"+this.user.get("username")};if(this.include)a.include=this.include;Backbone.Collection.prototype.fetch.call(this,{data:a})}}),o=Backbone.Collection.extend({model:b.Post,url:DISQUS.urls.api+"users/listPostActivity"}),n=Backbone.Collection.extend({model:b.TopThread,url:DISQUS.urls.api+
"threads/listPopular",initialize:function(a,b){this.forum=b.forum;this.limit=b.limit},add:function(a,b){_.isArray(a)||(a=[a]);var d=[];_.each(a,function(a){a.title.match(/^http/i)||d.push(a)});Backbone.Collection.prototype.add.call(this,d,b)},fetch:function(){Backbone.Collection.prototype.fetch.call(this,{data:{forum:this.forum,limit:this.limit,interval:"7d",with_top_post:!0}})}}),r=Backbone.Collection.extend({model:b.TopUser,url:DISQUS.urls.api+"forums/listMostActiveUsers",initialize:function(a,
b){this.forum=b.forum;this.limit=b.limit},fetch:function(){Backbone.Collection.prototype.fetch.call(this,{data:{forum:this.forum,limit:this.limit}})}}),u=f.extend({model:b.Reaction,url:DISQUS.urls.api+"threads/listReactions",initialize:function(a,b){this.thread=b.thread},fetch:function(a){a=a||{};a=_.extend(a,{data:{limit:u.PAGINATION_LIMIT,thread:this.thread.id}});return f.prototype.fetch.call(this,a)}},{PAGINATION_LIMIT:20});return{UserCollection:i,PostCollection:h,ReactionsCollection:u,TypingUserCollection:l,
TopUserCollection:r,TopThreadCollection:n,VoteCollection:j,ThreadVoteCollection:d,ActivityCollection:m,PostActivityCollection:o,NotificationCollection:a,QueuedPostCollection:q,SwitchCollection:k}});
DISQUS.define("lounge.views",function(){var b=DISQUS.use("lounge.models"),e=DISQUS.use("lounge.collections"),d=DISQUS.use("lounge.utils"),i=DISQUS.use("lounge.realtime"),a=DISQUS.use("Bus"),j=DISQUS.use("JSON"),f,h=1,q={shareTwitter:function(){var c=this,a=this.model instanceof b.Post&&this.model,d=this._shareUrl(),e=DISQUS.serialize(DISQUS.urls.loading,{img:DISQUS.urls.themeUrl+"/img/loader.gif"}),O=window.open(e,"_blank","width=550,height=520"),C=DISQUS.serialize("https://twitter.com/intent/tweet",
{url:d}),d={url:d,source:"disqus_embed_next",forum:this.thread.get("forum"),thread:this.thread.get("id")};if(a)d.post=a.id;DISQUS.api.call("shortener/create.json",{method:"POST",data:d,timeout:5E3,success:function(b){var d=140,e,t=b.response;b.code===0&&(a?(e=a.author.get("name")||a.author.get("username"),d-=e.length+3,d-=t.url.length+1,d-=2,b=a.messageText(),b=DISQUS.lounge.utils.niceTruncate(b,d),b='"'+b+'" \u2014 '+e):(b=c.thread.get("title"),b=DISQUS.lounge.utils.niceTruncate(b,d)),C=DISQUS.serialize("https://twitter.com/intent/tweet",
{url:t.url,text:b}))},complete:function(){O.location=C;f.trigger("uiAction:postShare","twitter")}})},shareFacebook:function(){var c=this._shareUrl();window.open(DISQUS.serialize("https://www.facebook.com/sharer.php",{u:c}),"_blank","width=655,height=352");f.trigger("uiAction:postShare","facebook")}},k=Backbone.View.extend({STREAMING_MAX_VISIBLE:250,initialize:function(c){f=this;c=c||{};c=c.jsonData||{};this.initialData=c.response||{};this.theme=this.initialData.theme;this.session=new b.User;this.forum=
new b.Forum;this.thread=new b.Thread(null,{forum:this.forum,postCursor:c.cursor,moderators:(this.initialData.thread||{}).moderators});this.posts=this.thread.posts;this.switches=new e.SwitchCollection;this.renderJobs=[];this.states={templateReady:!1,realtimeIndicatorsCreated:!1,pollingRunning:!1,ravenConfigured:!1,inViewport:!1,streamingPaused:!1};a.bind("window.inViewport",function(){this.states.inViewport=!0;this.trigger("inViewport")},this);a.bind("window.scrollOffViewport",function(){this.states.inViewport=
!1},this);a.bind("switches.changed",function(c){this.switches.reset(this.switches.parse(c));if(!this.states.ravenConfigured&&this.switches.enabled("next_raven"))Raven.config({servers:["http://disqus.com/raven/report/"],logger:"javascript.next"}),window.onerror=Raven.process,DISQUS.api.defaults({error:function(c){Raven.captureMessage({name:"API call failed.",message:c})}}),this.states.ravenConfigured=!0;if(!this.switches.enabled("next_lazy_embed")||this.states.inViewport)this.initializeSession();else this.on("inViewport",
this.initializeSession,this)},this);this.switches.on("reset",function(){var c=function(){if(!this.states.templateReady)return!1;return this.thread&&this.thread.id};DISQUS.defer(_.bind(c,this),_.bind(this.poll,this));DISQUS.defer(_.bind(c,this),_.bind(this.renderThreadVotes,this,this.thread))},this);a.bind("init",function(c){f.bootstrap(c)});a.sendHostMessage("ready")},bootstrap:function(c){var g=this;g.config=c||{};c.apiKey&&DISQUS.api.defaults({headers:{"X-Disqus-Remote-Auth":c.remoteAuthS3,"X-Disqus-Publisher-API-Key":c.apiKey}});
c.anchorColor&&function(){var a=d.escapeColor(c.anchorColor);d.addStylesheetRules([[".publisher-anchor-color a",["color",a,!0]],["a.publisher-anchor-color",["color",a,!0]]])}();c.serif&&$("body").addClass("serif");(function(){var a=document.createElement("base");a.target="_parent";a.href=c.referrer;$("head").append(a)})();if(c.width)document.body.style.width=c.width+"px";if(c.permalink)g.on("postsRendered",_.once(function(){g.scrollToPost(c.permalink)}));if(c.sso)DISQUS.templateGlobals.sso=c.sso;
var b=this.theme.js,e=this.theme.css;c.themeUrl&&(b=c.themeUrl+"/theme.js",e=c.themeUrl+"/theme.css");DISQUS.urls.themeUrl=c.themeUrl||this.theme.root;DISQUS.requireStylesheet(e,{},DISQUS.debug);DISQUS.require(b,{},DISQUS.debug,function(){g.renderLayout();c.colorScheme==="dark"&&$("body").addClass("dark");g.states.templateReady=!0;g.trigger("templateReady")});g.bind("templateReady",g.renderForm,g);g.bind("templateReady",g.updatePostCount,g);g.bind("templateReady",g.initCommunity,g);g.bind("templateReady",
g.initReactions,g);g.bind("templateReady",g.updateSurveyMonkeyUrl,g);g.bind("templateReady",g.renderStreamingToggle,g);g.renderBindings([g.thread,"change:likes",g.updateThreadVotes],[g.thread,"change:userScore",g.updateThreadUserScore],[g.thread,"change:posts",g.updatePostCount],[g.thread,"change:isClosed",g.toggleUserMenu],[g.thread,"change:userSubscription",g.renderThreadVotes],[g.thread.posts,"reset",g.redrawPosts],[g.thread.posts,"add",g.addPosts],[g.thread.posts,"remove",g.removePost],[g.thread.posts,
"reset add",g.toggleLoadMorePosts],[g.thread.posts,"reset add",g.toggleNoPosts],[g.thread.posts,"reset",g.poll],[g.thread.reactions,"reset add",g.toggleLoadMoreReactions],[g.session,"change:id",g.renderForm],[g.session,"change:id",g.toggleUserMenu],[g.session,"change:id",g.updateThreadSessionData],[g.session,"change:id",g.initDashboard],[g.session,"change:id",g.updateHelpNotice],[g.session,"change:id",g.updateSurveyMonkeyUrl],[g.session,"change:id",g.renderDebugInfo],[g.session,"change:id",g.renderThreadVotes]);
g.bind("scroll",function(c){g.position=c;if(g.currentSection==="conversation")g.conversationPosition=c});g.bind("scrollOffViewport",function(){g.states.realtimeIndicatorsCreated&&g.currentSection==="conversation"&&(a.sendHostMessage("realtime.hideNorth"),a.sendHostMessage("realtime.hideSouth"))});g.bind("scroll",function(c){if(g.states.realtimeIndicatorsCreated&&g.currentSection==="conversation"){var b=_.union([this.queueView],_.values(this.postViews)),d=0,e=0;_.each(b,function(a){if(a&&!a.getDirection)a=
a.queueView;if(a&&!(a.options.count<=0)){var g=a.getDirection(c);g===1?d+=a.options.count:g===-1&&(e+=a.options.count)}});var b="realtime.hideNorth",t;d>0&&(b="realtime.showNorth",t=DISQUS.renderBlock("realtimeIndicatorText",{num:d,orientation:"north"}));a.sendHostMessage(b,t);b="realtime.hideSouth";t=void 0;e>0&&(t=DISQUS.renderBlock("realtimeIndicatorText",{num:e,orientation:"south"}),b="realtime.showSouth");a.sendHostMessage(b,t)}},g);a.bind("window.hashchange",function(c){(c=c&&c.match(/comment\-([0-9]+)/))&&
g.scrollToPost(c[1])});a.bind("window.scroll",function(c){g.trigger("scroll",c)});a.bind("window.scrollOffViewport",function(){g.trigger("scrollOffViewport")});a.bind("window.resize",g.resize,g);a.bind("realtime.click",function(c){a.sendHostMessage("realtime.hide"+(c==="north"?"North":"South"));var b=_.union([g],_.toArray(g.postViews)),d,e,b=_.filter(b,function(a){a=a.queueView;if(!a||a.options.count<=0)return!1;var b=c==="north"?1:-1;if(a.getDirection(g.position)!==b)return!1;return!0}),b=_.sortBy(b,
function(c){if(c===g)return 0;return c.offset.top}),b=c==="north"?_.last(b):_.first(b);d=b.queueView;b===g?(e=0,d.model.queue.drain(),d.setCount(d.model.queue.length)):(e=b.offset.top-100,d.options.thread.queue.drain(d.model.id),d.setCount(d.options.thread.queue.length));var t=function(){a.sendHostMessage("scrollTo",{top:e});k.getInstance().off("domReflow",t)};k.getInstance().on("domReflow",t)});g.thread.queue.bind("add reset",g.toggleRealtimeNotifications,g);g.forum.set(this.initialData.forum);g.thread.set(this.initialData.thread);
g.posts.reset(this.initialData.posts);if(g.forum.get("settings").ssoRequired)g.session.get("thread").canReply=!1;a.bind("auth:success",function(c){c.sessionId&&DISQUS.api.defaults({headers:{"X-Sessionid":c.sessionId}});g.refreshSession()});setTimeout(function C(){g.postViews&&!(_.size(g.postViews)<1)&&(_.invoke(g.postViews,"updateRelativeTime"),setTimeout(C,6E4))},6E4);g.currentSection="conversation";g.initialized=!0},initializeSession:function(){var c=this;(!c.forum.get("settings").ssoRequired||
c.config.remoteAuthS3)&&c.session.fetchSession({thread:c.thread,complete:function(){c.session.trigger("identify");c.session.on("authenticated",c.refreshSession,c)}})},refreshSession:function(){this.session.fetchSession({thread:this.thread})},initRealtime:function(){var c={width:$("html").width()+"px",position:"fixed"},g={contents:DISQUS.renderBlock("realtimeIndicator",{orientation:"north"}),styles:{top:"0"}},b={contents:DISQUS.renderBlock("realtimeIndicator",{orientation:"south"}),styles:{bottom:"0"}};
_.defaults(g.styles,c);_.defaults(b.styles,c);a.sendHostMessage("realtime.init",{north:g,south:b});this.states.realtimeIndicatorsCreated=!0},insertStreamingComments:_.throttle(function(){var c=this.thread.queue;c.drain();_.each(c.counters.replies,function(a,b){c.drain(b)})},1E3),toggleRealtimeNotifications:function(){var c=this,g=c.thread.queue;c.updateDom(function(){_.defer(function(){a.sendHostMessage("fakeScroll")});if(!g.length)return void $("[data-role=realtime-notification]").hide();if(c.thread.get("hasStreaming"))return void c.insertStreamingComments();
var b=c.queueView||new A({model:c.thread,el:c.$el.find("button[data-role=realtime-notification]")});c.queueView=b;b.setCount(g.counters.comments);b.render();_.each(g.counters.replies,function(a,g){var b=c.thread.posts.get(g);if(b){var d=c.postViews[b.cid],e=d.queueView;if(!e)e=new v({thread:c.thread,postView:d,model:b,el:d.$el.find("[data-role=realtime-notification:"+g+"] a")}),d.queueView=e;e.setCount(a);e.render()}})})},renderDebugInfo:function(){if(this.session.get("isGlobalAdmin")){var c=new R({thread:this.thread});
c.render();document.body.appendChild(c.el)}},scrollToPost:function(c,g,d){var e=this;e.currentSection!=="conversation"&&(d=!0);e.mainNav.navTo("conversation");var f=e.$el.find("#post-"+c);f.length?(g=g||0,setTimeout(function(){a.sendHostMessage("scrollTo",{top:f.offset().top+g,force:d||null})},100)):DISQUS.api.call("posts/getContext.json",{method:"GET",data:{post:c},success:function(a){a=_.filter(a.response,function(c){return c.thread==e.thread.get("id")});a.length!==0&&(_.each(a,function(c){e.thread.posts.add(new b.Post(c))}),
e.on("domReflow",function Q(){e.off("domReflow",Q);e.scrollToPost(c,g,d)}))}})},updateThreadSessionData:function(c){c&&(c.get("thread")&&this.thread.set(c.get("thread")),(c=c.get("votes"))&&typeof c==="object"&&_.each(c,function(c,a){var b=this.posts.get(a);b&&b.set("userScore",c)},this))},updateSurveyMonkeyUrl:function(){var c=this.$el.find("#surveymonkey");if(c.length){var a=this.config.referrer,b=this.session.id,a="?c="+encodeURIComponent((b?[b,a]:[a]).join(";")),a=c.attr("href").replace(/(\?.*)?$/,
a);c.attr("href",a)}},updateHelpNotice:function(){if(DISQUS.blocks.helpNotice){var c=DISQUS.renderBlock("helpNotice",{isModerator:this.session.get("thread").canModerate});this.updateDom(function(){this.$el.find("#help-notice").html(c)},this)}},initDashboard:function(){var c=$("#main-nav [data-nav=dashboard]");if(!this.session.id)return c.hide();c.show();this.notifications=new e.NotificationCollection(null,{user:this.session});this.notifications.fetch();this.notificationCount=new p({el:c.find("[data-role=notification-count]")[0],
collection:this.notifications});this.dashboard=new G({el:$("#dashboard")[0],user:this.session,notifications:this.notifications})},initCommunity:function(){this.community=new J({el:document.getElementById("community"),forum:this.forum})},initReactions:function(){this.reactions=new S({el:$("#reaction-list")[0],collection:this.thread.reactions,thread:this.thread,session:this.session});this.forum.get("settings").hasReactions&&$("#global-nav").length===0&&(this.thread.reactions.on("reset",function(){$("#reactions").show()}),
this.thread.reactions.fetch())},toggleLoadMorePosts:function(){var c=this.$el.find("#posts [data-role=more]");this.updateDom(function(){c[this.thread.posts.cursor.hasNext?"show":"hide"]()},this)},toggleLoadMoreReactions:function(){var c=this.$el.find("#reactions [data-role=more]");this.updateDom(function(){c[this.thread.reactions.cursor.hasNext?"show":"hide"]()},this)},toggleUserMenu:function(){var c=this.$el.find("[data-role=logout]");this.updateDom(function(){this.session.id?(c.html(DISQUS.renderBlock("userMenu",
{user:this.session.toJSON(),thread:this.thread.toJSON(),sso:this.config.sso})),c.show()):c.hide()},this)},poll:function(){function c(c){var c=c.message_body,d=a.thread;if(!a.thread.get("hasStreaming")||!a.states.streamingPaused){if(!c.id)return void DISQUS.log("RT: no post ID");if(!c.author||!c.author.id)return void DISQUS.log("RT: no author or author ID");if(!c.author.name||!c.author.email_md5)return void DISQUS.log("RT: no author name or email hash");if(!c.post||!c.post.message)return void DISQUS.log("RT: no post message");
if(d.posts.get(c.id)||d.queue.get(c.id))return void DISQUS.log("RT: duplicate",c.id);if(c.type!=="approved"||c.type_prev!==null)return void DISQUS.log("RT: unnaproved",c.id);a.thread.incrementPostCount(1);var e=c.post.parent_post.id;if((e=e!=="0"?e:null)&&!d.posts.get(e)&&!d.queue.get(e))return void DISQUS.log("RT: parent is not on this page",c.id);var f=c.author.id==="0"?c.author.email_md5:c.author.id,z=d.users.get(f);z||(z=new b.User({id:f,name:c.author.name,emailHash:c.author.email_md5,isAnonymous:c.author.id===
"0"}),c.author.avatar&&z.set("avatar",{cache:c.author.avatar,pemalink:c.author.avatar}),d.users.add(z));d.queue.add({id:c.id,userId:z.get("id"),parentId:e,message:c.post.message})}}var a=this;if(a.switches.enabled("next_realtime")&&!a.states.pollingRunning){a.states.pollingRunning=!0;a.switches.enabled("next_realtime:indicators")&&(a.states.realtimeIndicatorsCreated||a.initRealtime());var d=new i.Firehose(DISQUS.urls.realertime+"/api/2/thread/"+a.thread.id);d.on("success",function(){a.states.pollingRunning=
!1;h=1;a.poll()});d.on("error",function(){h<=120&&(h*=2);a.states.pollingRunning=!1;_.delay(_.bind(a.poll,a),h*1E3)});d.on("progress",function(d){switch(d.message_type){case "Post":c(d);break;case "Vote":var e=d.message_body,f=a.thread.posts.get(e.vote.recipient_post_id);e.id&&e.vote&&!(a.session.id&&e.vote.voter_id==a.session.id)&&f&&(d=f.votes.get(e.id),d||(d=new b.Vote({id:e.id}),f.votes.add(d)),e=f._vote(e.vote.vote,d.get("score")),e!==0&&d.set("score",e));break;case "ThreadVote":e=d.message_body;
f=a.thread;e.id&&e.vote&&!(a.session.id&&e.vote.voter_id==a.session.id)&&(d=f.votes.get(e.id),d||(d=new b.ThreadVote({id:e.id}),f.votes.add(d)),e=f._vote(e.vote.vote,d.get("score")),e!==0&&d.set("score",e));break;case "IsTyping":e=d.message_body,f=a.thread,e.thread_id==f.id&&e.post.parent_post.id&&(e=f.posts.get(e.post.parent_post.id))&&(e.usersTyping.get(d.firehose_id)||(!(e.usersTyping.count()<=0)||d.typing)&&e.usersTyping.add(new b.TypingUser({id:d.firehose_id,typing:d.typing})))}});d.run()}},
_shareUrl:function(){var c=this.thread.get("url")||this.thread.get("link");if(!c&&this.config)c=this.config.referrer;return c},renderBindings:function(){var c=this;_.each(arguments,function(a){var b=a[2];a[0].bind(a[1],function(){var a=arguments;c.states.templateReady?b.apply(c,a):c.bind("templateReady",function(){b.apply(c,a)})})})},updateDom:function(c,a){this.renderJobs.push([c,a]);this._updateDom()},_updateDom:_.debounce(function(){for(var c,a;this.renderJobs.length;)c=this.renderJobs.shift(),
a=c[0],c=c[1],a&&a.call(c);this.resize();this.trigger("domReflow")},0),subscribe:function(c,a){this.thread.subscribe(!0,a);this.alert("You have subscribed to this thread.","success")},unsubscribe:function(){this.thread.subscribe(!1);this.alert("You have unsubscribed from this thread.","success")},renderThreadVotes:_.debounce(function(){var c=this,a=$(DISQUS.renderBlock("threadVotes",{thread:c.thread.toJSON(),sharing:c.switches.enabled("next_thread_sharing"),user:c.session.toJSON()}));c.delegateActions($(a),
{upvote:function(){c.handleThreadVote(1)},downvote:function(){c.handleThreadVote(-1)},"share:twitter":"shareTwitter","share:facebook":"shareFacebook",subscribe:"subscribe",unsubscribe:"unsubscribe"});a.find("#thread-subscribe-email").click(function(c){c.stopPropagation()}).on("keydown",function(a){if(!(a.key!=="Enter"&&a.keyCode!==13))a=a.target.value,d.validateEmail(a)?c.subscribe(!0,a):c.alert("Please enter a valid e-mail to subscribe.")});this.updateDom(function(){$("#thread-votes").empty();$("#thread-votes").append(a[0])})},
200),renderStreamingToggle:function(){var c=this;if(c.thread.get("hasStreaming")&&DISQUS.blocks.realtimeToggleButton){var a=$(DISQUS.renderBlock("realtimeToggleButton"));$(a).bind("click",function(){c.toggleStreamingRealtime()});c.updateDom(function(){$("#realtime-toggle").empty();$("#realtime-toggle").append(a[0])})}},toggleStreamingRealtime:function(){var c=$("#realtime-toggle a.btn");this.states.streamingPaused?(this.states.streamingPaused=!1,c.addClass("pause")):(this.states.streamingPaused=!0,
c.removeClass("pause"))},updateThreadVotes:function(){$("#thread-votes [data-role=like-count]").text(this.thread.get("likes"))},updateThreadUserScore:function(){var c=this.thread.get("userScore"),a=$("#thread-votes [data-role=vote-button]");a.length?(a.removeClass("upvoted").removeClass("downvoted"),c>0?a.addClass("upvoted"):c<0&&a.addClass("downvoted")):_.defer(_.bind(this.updateThreadUserScore,this))},handleThreadVote:function(c){c===1?f.trigger("uiAction:threadUpvote"):c===-1&&f.trigger("uiAction:threadDownvote");
var a=this.thread.get("userScore")===c;a||_.defer(function(){$("#thread-votes [data-role=vote-button] .dropdown").addClass("open")});this.thread.vote(a?0:c)},updatePostCount:function(){$("#post-count").html(DISQUS.renderBlock("postCount",{count:this.thread.get("posts")}))},swapMain:function(c){var g=this,b=this.$el.find("#main-nav [data-nav=conversation]").parent("li");c!=="conversation"?b.attr("data-dropdown","disabled"):b.attr("data-dropdown","enabled");g.updateDom(function(){g.states.realtimeIndicatorsCreated&&
c!="conversation"&&(a.sendHostMessage("realtime.hideNorth"),a.sendHostMessage("realtime.hideSouth"));var b=g[c];b&&!b.isRendered&&(g.freeze(!0),b.on("render:all",_.once(function(){g.freeze(!1)})),b.show());g.$el.find("[data-role=main]").hide();g.$el.find("[data-role=main]#"+c).show();g.prevSection=g.currentSection;g.currentSection=c})},returnToConversation:function(){this.mainNav.navTo("conversation");var c=this.conversationPosition,g=c&&c.pageOffset;g&&this.updateDom(function(){setTimeout(function(){a.sendHostMessage("scrollTo",
{top:g,relative:"window",force:!0})},100)},this)},setupNavigation:function(){var c=this;c.globalNav=new K({el:c.$el.find("#global-nav")[0]});c.mainNav=new K({el:c.$el.find("#main-nav")[0]});c.globalNav.on("nav",function(a){c.updateDom(function(){var b=c.$el.find("#form"),d=c.$el.find("#main-nav");switch(a){case "conversation":b.show();d.show();c.swapMain(c.prevSection||a);break;case "reactions":b.hide(),d.hide(),c.swapMain(a)}})});c.mainNav.on("nav",function(a){c.updateDom(function(){c.swapMain(a)})})},
renderLayout:function(){function c(c){return function(b){b.preventDefault();var d=$(b.currentTarget);d.addClass("busy");a.thread[c].more({success:function(){d.removeClass("busy")},error:function(){d.removeClass("busy")}})}}var a=this;a.setElement($(DISQUS.renderBlock("layout",{thread:_.extend(a.thread.toJSON(),{showToggler:!0,showReactions:a.forum.get("settings").hasReactions}),order:a.thread.posts.order})).appendTo("body"));var b=a.$el;a.delegateActions(a.$el,{profile:function(c){c=$(c.currentTarget).attr("data-user");
(c=a.thread.users.get(c))&&a.showProfile(c)},logout:function(){a.session.logout()},sort:function(c){var a=$(c.currentTarget),c=a.closest("li"),a=a.attr("data-sort");c.siblings().removeClass("selected");c.addClass("selected");this.thread.posts.order=a;this.thread.posts.fetch();$("#conversation-menu").removeClass("open");$("#posts [data-role=more]").hide();$("#post-list").addClass("loading").empty()},"close-thread":function(){a.alert("Comments are now closed. Please refresh this page to see how it would look to visitors.");
a.thread.close()},"open-thread":function(){a.alert("Comments are now open. Please refresh this page to see how it would look to visitors.");a.thread.open()}});a.setupNavigation();_.each(["posts","reactions"],function(a){b.delegate("[data-action=more-"+a+"]","click",c(a))});a.resize()},alert:function(c,a){this._alert&&this._alert.dismiss();var b=this._alert=new E({message:c,type:a});b.render().$el.prependTo($("#form")[0]);return b},renderForm:function(){if(this.thread.get("isClosed"))return void this.alert("Comments for this thread are now closed.");
if(this.session.get("thread").canReply){this.postForm&&this.updateDom(function(){this.postForm.remove()},this);var c=this.postForm=new o({thread:this.thread,session:this.session});c.render();this.updateDom(function(){$("#form").prepend(c.el);c.resize()},this);this.resize()}},toggleNoPosts:function(){this.updateDom(function(){var c=this.thread.posts.models;$("#no-posts")[c.length?"hide":"show"]();$("#post-list").removeClass("loading")},this)},redrawPosts:function(){var c=this;c.postViews={};c.addPosts(c.thread.posts,
{clearDom:!0});_.each(o.open,function(a,b){var d=c.postViews[b];d&&(d.toggleReply(),d.reply.textarea.set(a.textarea.get()))})},addPosts:function(c,a,d){var f=this,h=[];if(c instanceof e.PostCollection)h=c.models,d=a||{};else if(c instanceof b.Post)h=[c],d=d||{};else throw"Not a post: "+typeof c;if(h.length){var i=[];_.each(h,function(c){var a=new r({model:c,thread:f.thread,session:f.session});f.postViews[c.cid]=a;a.render();c.get("isRealtime")&&f.removeOldPosts.call(f);(c=c.get("parent"))?(c=f.thread.posts.get(c))&&
f.postViews[c.cid].attachChild(a):i.push(a.el)});i.length&&f.updateDom(function(){var c=$("#post-list");d.clearDom&&c.empty();$("#post-list").removeClass("loading");d.created||!h[0].id||h[0].get("isRealtime")?c.prepend(i):c.append(i);f.trigger("postsRendered")})}},showProfile:function(c){this.profile&&this.profile.remove();var b=this.profile=new F({user:c,session:this.session});this.freeze(!0);this.updateDom(function(){this.mainNav.clear();$("#profile").empty().append(b.el);this.swapMain("profile");
b.show()},this);b.bind("close",function(){this.returnToConversation();this.updateDom(function(){b.remove()},this)},this);b.bind("render:all",_.once(function(){this.freeze(!1)}),this);a.sendHostMessage("scrollTo",{top:0})},removePost:function(c){var a=this.postViews[c.cid];a&&(a.remove(),delete this.postViews[c.cid])},removeOldPosts:_.debounce(function(){if(this.switches&&this.switches.enabled("next_realtime_cap")){var c=_.size(this.postViews)-this.STREAMING_MAX_VISIBLE;if(!(c<=0))for(var a=this.thread.posts.sortBy(function(c){return moment(c.get("createdAt")).valueOf()}),
b,d=0,e=0;d<a.length&&e<=c;d++)if((b=this.postViews[a[d].cid])&&b.childrenNode.children().length===0)this.thread.posts.remove(a[d]),e+=1}},500),resize:function(){var c=$("body").height();if(!this._frozen||!(this._lastHeight&&this._lastHeight>c))this._lastHeight=c,a.sendHostMessage("resize",{height:c})},freeze:function(c){this._frozen=!!c;this._frozen===!1&&this.resize()},getPostView:function(c){return this.postViews[c]}});k.getInstance=function(){return f};_.extend(k.prototype,q);var l=Backbone.View.extend({updateDom:function(c,
a){var b=k.getInstance();b&&b.initialized?b.updateDom(c,a):_.isFunction(c)&&c.call(a)},resize:function(){var c=k.getInstance();c&&c.initialized&&c.resize()}}),m=new QueuedStorage(DISQUS.browser.localStorage?window.localStorage:DISQUS.lounge.utils.hashStorage,5,"drafts.queue"),o=l.extend({events:{"click [data-action=auth-twitter]":"authTwitter","click [data-action=auth-facebook]":"authFacebook","click [data-action=auth-google]":"authGoogle","click [data-action=auth-disqus]":"authDisqus","click [data-action=auth-sso]":"authSSO",
"click [data-nav]":"showAuthSection","click [name=author-register]":"expandRegister"},initialize:function(c){this.session=c.session;this.parent=c.parent;this.thread=c.thread;this.parentView=c.parentView;this.thread.bind("change:id",function(){this.restoreDraft()},this);this.session.bind("change:id",this.redraw,this);this.parent&&(o.open[this.parent.cid]=this);this.textarea=DISQUS.browser.contentEditable&&!DISQUS.browser.mobile?new B({thread:this.thread}):new D},storageKey:function(){if(!this.thread.id)return null;
return["drafts:thread",this.thread.id,"parent",this.parent?this.parent.id:0].join(":")},saveDraft:function(){this.storageKey()!==null&&m.setItem(this.storageKey(),j.stringify([this.textarea.get(),(new Date).getTime()]))},getDraft:function(){if(this.storageKey()===null)return null;var c=m.getItem(this.storageKey());if(!c)return null;c=j.parse(c);if(c[1]+86400>(new Date).getTime())return c[0];m.removeItem(this.storageKey());return null},restoreDraft:function(){this.textarea.set(this.getDraft())},updateAvatar:function(){this.$el.find("[data-role=user-avatar]").attr("src",
this.session.get("avatar").cache)},authTwitter:function(c){c&&c.preventDefault()&&c.preventDefault();window.open(DISQUS.urls.oauth.twitter,"_blank","width=650,height=440")},authFacebook:function(c){c&&c.preventDefault()&&c.preventDefault();window.open(DISQUS.urls.oauth.facebook,"_blank","width=550,height=300")},authGoogle:function(c){c&&c.preventDefault()&&c.preventDefault();window.open(DISQUS.urls.oauth.google,"_blank","width=650,height=440")},authDisqus:function(c){c&&c.preventDefault()&&c.preventDefault();
window.open(DISQUS.urls.login,"_blank","width=460,height=355")},authSSO:function(c){c&&c.preventDefault()&&c.preventDefault();if(c=k.getInstance()){var b=window.open(c.config.sso.url,"_blank","width=800,height=500");(function t(){d.isWindowClosed(b)?a.sendHostMessage("reload"):_.delay(t,500)})()}},expandGuestForm:function(){this.$el.find("[data-role=guest-details]").addClass("expanded")},expandRegister:function(){this.$el.toggleClass("register")},redraw:function(){var c=this.el,a=this.$el.find("textarea").val();
this.render();this.$el.find("textarea").val(a);this.session.id&&this.$el.addClass("expanded");c.parentNode&&this.updateDom(function(){c.parentNode.replaceChild(this.el,c)},this)},render:function(){var c=this,a=c.getDraft()||"";this.setElement($(DISQUS.renderBlock("form",{message:a,parent:c.parent?c.parent.toJSON():null,user:c.session.toJSON(),allowAnonPost:c.thread.forum.get("settings").allowAnonPost})));this.$el.find("form").bind("submit",_.bind(this.submitForm,this));a=this.textarea;a.setElement(c.$el.find("textarea")[0]);
a.render();a.bind("keychange",this.saveDraft,this);a.$el.bind("focus",function(){c.$el.addClass("expanded focus");_.delay(_.bind(c.resize,c),200)});a.$el.bind("blur",function(){c.$el.removeClass("focus")});c.$el.find("input[name=author-name]").bind("focus",function(){c.expandGuestForm()});c.typingStart()},resize:function(){this.textarea.resize()},showAuthSection:function(c){c&&c.preventDefault&&c.preventDefault();var a=c.currentTarget.getAttribute("data-nav");this.updateDom(function(){var c=this.$el.find("[data-nav]");
_.each(c,function(c){$(c.parentNode).removeClass("active")});this.$el.find("[data-nav="+a+"]").parents("*").addClass("active");this.$el.find("section").hide();this.$el.find("[data-tab="+a+"]").show()},this)},focus:function(){this.textarea.focus()},clear:function(){var c=this;c.textarea.clear();c.$el.removeClass("expanded");setTimeout(function(){c.resize()},200);c.parent&&c.$el.hide();this.storageKey()&&m.removeItem(this.storageKey())},restore:function(c){var a=this;a.textarea.set(c.get("raw_message"));
setTimeout(function(){a.resize()},200);a.parent&&a.$el.show()},alert:function(c){this._alert&&this._alert.remove();(this._alert=new E({message:c,type:"error"})).render().$el.prependTo(this.el)},submitForm:function(c){var a=this;c&&c.preventDefault&&c.preventDefault();if(this._alert)this._alert.remove(),this._alert=null;c=a.$el.find("input[name=author-register]");c=c.length&&c[0].checked;return!a.session.id&&c?(a.session.register({name:a.$el.find("input[name=author-name]").val(),email:a.$el.find("input[name=author-email]").val()},
{error:function(){a.alert("That email address is already registered with a Disqus account. Log in or enter another email.")}}),null):a.createPost()},createPost:function(){var c=this,a={thread:c.thread.id,depth:c.parent?c.parent.get("depth")+1:0,parent:c.parent?c.parent.id:null,raw_message:c.textarea.get()};c.session.id?a.author_id=c.session.id:_.extend(a,{author_name:c.$el.find("input[name=author-name]").val(),author_email:c.$el.find("input[name=author-email]").val()});var d=new DISQUS.lounge.models.Post;
if(d.set(a,{error:function(a,b){c.alert(b)}})){var e=null,h=function(a,b){if(b.code===19){if(e)return e.reload();e=new u;e.render();var g=f.getPostView(d.cid);g.el.parentNode.insertBefore(e.el,g.el);e.start();e.bind("submitted",function(){d.save({recaptcha_challenge_field:e.getChallenge(),recaptcha_response_field:e.getResponse()},{success:function(){e.remove()}})})}else c.thread.posts.remove(d),c.restore(d),b.response&&c.alert(b.response),c.thread.incrementPostCount(-1)};this.$el.find("input[name=author-register]");
d.on("error",h);d.on("sync",function P(){d.off("error",h);d.off("sync",P)});d.save(a);d.author=c.session.id?c.session:new b.User({id:md5(a.author_email),name:a.author_name,email:a.author_email});c.thread.posts.add(d,{created:!0});c.clear();c.trigger("submitted");c.thread.incrementPostCount(1);f.trigger("uiAction:createPost",d);return d}},remove:function(){this.updateDom(function(){this.$el.remove()},this);this.parent&&(delete o.open[this.parent.cid],this.typingStop())},toggle:function(){this.$el.toggle();
this.isOpen()?this.typingStart():this.typingStop()},isOpen:function(){return this.el.style.display!=="none"},typingStart:function(){var c=this;if(c.parent){var a=k.getInstance();a.switches&&a.switches.enabled("next_realtime")&&setTimeout(function(){var a=DISQUS.urls.realertime+"/api/2/typing/",b;d.attempt(function(){b=d.makeCORSRequest("POST",a)});if(b===null)return void DISQUS.log("CORS is not supported by this browser.");var g=j.stringify({typing:!0,forum_url:c.thread.get("forum"),thread_id:c.thread.get("id"),
user_id:c.session.id||0,parent_post_id:c.parent.get("id")});d.attempt(function(){b.send(g)})},500)}},typingStop:function(){var c=this;if(c.parent){var a=k.getInstance();a.switches&&a.switches.enabled("next_realtime")&&setTimeout(function(){var a=DISQUS.urls.realertime+"/api/2/typing/",b;d.attempt(function(){b=d.makeCORSRequest("POST",a)});if(b===null)return void DISQUS.log("CORS is not supported by this browser.");var g=j.stringify({typing:!1,forum_url:c.thread.get("forum"),thread_id:c.thread.get("id"),
user_id:c.session.id||0,parent_post_id:c.parent.get("id")});d.attempt(function(){b.send(g)})},500)}}});o.open=o.open||{};var n=l.extend({initialize:function(c){this.post=c.post;this.textarea=new D},render:function(){this.setElement($(DISQUS.renderBlock("edit",{post:this.post.toJSON()})));this.$el.find("form").bind("submit",_.bind(this.submitForm,this));var c=this.textarea;c.setElement(this.$el.find("textarea")[0]);c.render()},resize:function(){this.textarea.resize()},submitForm:function(c){c&&c.preventDefault()&&
c.preventDefault();var c={raw_message:this.textarea.get()},a=this.post.validate(c);if(a!==void 0)return alert(a);this.trigger("submitted");this.post.save(c,{success:function(){}})},remove:function(){this.updateDom(function(){this.$el.remove()},this)}}),r=l.extend({MAX_INDENT_DEPTH:3,initialize:function(c){this.thread=c.thread;this.session=c.session;this.model.bind("destroy",this.removeAsDeleted,this);this.model.bind("spam",this.removeAsDeleted,this);this.model.bind("change:id",this.redraw,this);this.model.bind("change:points",
this.updatePoints,this);this.model.bind("change:message",this.updateMessage,this);this.model.bind("change:message",this.stopLoading,this);this.model.bind("change:userScore",this.updateVotes,this);this.model.usersTyping.bind("add remove reset",this.updateTypingCount,this);this.session.bind("change:id",this.updateEditHide,this);this.session.bind("change:id",this.updateFooter,this);this.session.bind("change:thread",this.updateMenu,this);this.edit=this.reply=null;this.parentView=c.parentView;this.trackPosition=
!1;k.getInstance().on("domReflow",function(){if(this.trackPosition){var c=this.contentNode;this.offset=c.offset();this.dim=c.dim()}else this.offset={top:-1,height:-1},this.dim={height:-1,width:-1}},this)},updateTypingCount:function(){this.typingUserView&&this.typingUserView.render()},stopLoading:function(){this.contentNode.find(".loading").removeClass("loading")},updateRelativeTime:function(){this.contentNode.find("[data-role=relative-time]").text(this.model.getRelativeCreatedAt())},updateVotes:function(c){var a=
this.contentNode.find("[data-role=voting]"),b=DISQUS.renderBlock("postVotes",{post:{userScore:c.get("userScore"),points:c.get("points"),likes:c.get("likes"),dislikes:c.get("dislikes")}});this.updateDom(function(){a.html(b)})},updateEditHide:function(){var c=this.contentNode.find("[data-role=edit-hide]"),a=DISQUS.renderBlock("postEditHide",{post:{author:{id:this.model.author.id}},session:{id:this.session.id}});this.updateDom(function(){c.html(a)})},updateFooter:function(){var c=this.contentNode.find("footer"),
a=DISQUS.renderBlock("postFooter",{post:this.model.toJSON(),session:this.session.toJSON(),thread:this.thread.toJSON()});this.updateDom(function(){c.html(a)})},updateMenu:function(){var c=this.contentNode.find("[data-role=menu]"),a=DISQUS.renderBlock("postMenu",{thread:this.session.get("thread"),post:{id:this.model.id}});this.updateDom(function(){c.html(a)})},updatePoints:function(c){var a=function(c){setTimeout(function(){c.addClass("update");setTimeout(function(){c.removeClass("update")},1E3)},500)};
this.contentNode.find("[data-role=points], [data-role=likes], [data-role=dislikes]").each(function(b){var b=$(b),d=b.html(),e=c.get(b.attr("data-role")).toString();d!==e&&(b.removeClass("count-"+e),b.removeClass("count-"+d),b.html(e),a(b))})},updateMessage:function(){this.contentNode.find("[data-role=message]").html(this.model.get("message"));this.model.get("depth")>this.MAX_INDENT_DEPTH&&this.mentionParent()},markSeen:function(){function c(d){var e,f;if(!d)return!1;e=a.offset.top+d.frameOffset.top;
f=(f=e>d.pageOffset)&&e+a.dim.height<=d.pageOffset+d.height;if(!f)return!1;a.contentNode.addClass("seen");_.delay(function(){a.contentNode.removeClass("seen");a.contentNode.removeClass("new")},1E4);a.trackPosition=!1;b.off("scroll",c);return!0}var a=this,b=k.getInstance();if(!c(b.position))b.on("scroll",c,a);b.off("domReflow",a.markSeen)},mentionParent:function(){if(!(this.model.get("depth")<=this.MAX_INDENT_DEPTH)&&this.contentNode){var c=this.contentNode.find("[data-role=message]"),a=c.children().first();
a.length||(a=c);if(c=this.thread.posts.get(this.model.get("parent"))){var b=c.author.get("name")||c.author.get("username"),d=this.model.messageText().indexOf(b);d>-1&&d<25||$(DISQUS.renderBlock("mention",{url:c.author.get("profileUrl"),name:b})).prependTo(a)}}},render:function(){var a=this;a.setElement($(DISQUS.renderBlock("post",{post:a.model.toJSON(),session:a.session.toJSON(),thread:a.thread.toJSON(),loading:!a.model.id})));a.contentNode=a.$el.find("[data-role=post-content]");a.childrenNode=a.$el.find("[data-role=children]");
a.model.get("depth")>a.MAX_INDENT_DEPTH&&a.mentionParent();if(a.model.get("isRealtime"))k.getInstance().switches.enabled("next_realtime_anim_disabled")?a.contentNode.removeClass("new"):(a.trackPosition=!0,f.on("domReflow",a.markSeen,a));f.on("domReflow",_.once(function(){var b=a.$el.find("[data-role=realtime-notification:"+a.model.id+"] .realtime-replies");a.typingUserView=new w({parentView:a,model:a.model,el:b})}));a.processMentions();a.bindDomEvents()},redraw:function(){var a=this.$el;if(!a)throw Error("Old child not found on PostView.redraw");
var b=this.childrenNode.children();this.render();this.updateDom(function(){a[0].parentNode.replaceChild(this.el,a[0]);this.childrenNode.append(b)},this)},processMentions:function(){this.contentNode.find("[data-dsq-mention]").each(function(){$(this).addClass("mention")})},attachChild:function(a){var b=a.model;!b.id||b.get("isImmediateReply")?this.childrenNode.prepend(a.el):this.childrenNode.append(a.el)},toggleReply:function(){if(this.reply)return void this.reply.toggle();this.reply=new o({parentView:this,
parent:this.model,thread:this.thread,session:this.options.session});this.reply.bind("submitted",function(){this.reply.remove();this.reply=null},this);this.drawReply()},drawReply:function(){this.reply&&(this.reply.render(),this.updateDom(function(){var a=this.childrenNode[0];a.insertBefore(this.reply.el,a.firstChild);this.reply.focus()},this))},toggleEdit:function(){this.edit?(this.edit.remove(),this.edit=null,this.contentNode.find("[data-role=message]").show()):(this.edit=new n({post:this.model}),
this.edit.render(),this.edit.bind("submitted",this.toggleEdit,this),this.updateDom(function(){var a=this.contentNode.find("[data-role=message]");a[0].parentNode.insertBefore(this.edit.el,a[0]);a.hide();this.edit.resize()},this))},removeAsDeleted:function(){this.redraw()},bindDomEvents:function(){var a=this;a.delegateActions(a.contentNode,{upvote:function(){a.handleVote(1)},downvote:function(){a.handleVote(-1)},reply:"handleReply",flag:"handleFlag",edit:"handleEdit","delete":"handleDelete",spam:"handleSpam",
blacklist:"handleBlacklist",collapse:"handleCollapse",reveal:"handleReveal","share:twitter":"shareTwitter","share:facebook":"shareFacebook"});var b=a.$el.find(".hovercard");if(b.length)a.hovercard=x.create({session:a.session,user:a.model.author,targetElement:b})},_shareUrl:function(){return f._shareUrl()+"#comment-"+this.model.id},handleBlacklist:function(){if(!this.blacklist){var a=this.blacklist=new L({model:this.model});a.render();a.on("success cancel",function(){this.blacklist.remove();this.blacklist=
null},this);this.updateDom(function(){this.contentNode.find("[data-role=blacklist-form]").first().append(a.el)},this)}},handleCollapse:function(){this.updateDom(function(){this.$el.toggleClass("collapsed")},this)},handleVote:function(a){a===1?f.trigger("uiAction:postUpvote"):a===-1&&f.trigger("uiAction:postDownvote");var b=this.model.get("userScore")===a;this.model.vote(b?0:a);var d=this.contentNode.find("[data-role=voting]");d.removeClass("upvoted").removeClass("downvoted");b||(a>0?d.addClass("upvoted"):
a<0&&d.addClass("downvoted"))},handleReply:function(){this.toggleReply()},handleFlag:function(){window.confirm("Are you sure you want to flag this comment?")&&this.model.report()},handleEdit:function(){this.toggleEdit()},handleDelete:function(){this.model.destroy()},handleSpam:function(){this.model.spam()},handleReveal:function(){this.model.set("isMinimized",!1);this.redraw()}});_.extend(r.prototype,q);var u=l.extend({render:function(){var a=this;a.setElement($(DISQUS.renderBlock("captcha")));a.$el.bind("submit",
function(b){b.preventDefault();a.trigger("submitted")})},start:function(){function a(){b.updateDom(function(){Recaptcha.create("6LdKMrwSAAAAAPPLVhQE9LPRW4LUSZb810_iaa8u",b.el,{theme:"custom",custom_theme_widget:"recaptcha_widget"});b.$el.show()})}var b=this;typeof Recaptcha==="undefined"?DISQUS.require("//www.google.com/recaptcha/api/js/recaptcha_ajax.js",{},!1,a):a()},getChallenge:function(){return Recaptcha.get_challenge()},getResponse:function(){return Recaptcha.get_response()},reload:function(){Recaptcha.reload()}}),
p=l.extend({initialize:function(){this.collection.bind("add reset remove",this.render,this);this.render()},render:function(){this.$el.text(this.collection.length);this.collection.length>0?this.$el.show():this.$el.hide();return this}}),A=Backbone.View.extend({__type__:"QueuedPostView",getDirection:function(a){var b=a.pageOffset,d=this.offset.top+a.frameOffset.top;if(d+this.dim.height<b)return 1;if(d>b+a.height)return-1;return 0},setCount:function(a){this.options.count=a},bindDrain:function(a){if(!this.clickEvent)this.$el.attr("data-action")==
"load-queued-posts"?this.$el.bind("click",a):this.$el.delegate("[data-action=load-queued-posts]","click",a),this.clickEvent=!0},render:function(){var a=this;if(a.options.count===0)return void a.$el.hide();a.$el.html(DISQUS.renderBlock("realtimeCommentNotification",{comments:a.options.count}));a.bindDrain(function(){a.model.queue.drain();a.setCount(a.model.queue.length);a.render()});k.getInstance().on("domReflow",_.throttle(function(){if(a.options.count!==0)this.offset=a.$el.offset(),this.dim=a.$el.dim()},
400),this);a.$el.show()}}),v=A.extend({getDirection:function(a){this.offset=this.options.postView.offset;this.dim=this.options.postView.dim;a=A.prototype.getDirection.call(this,a);delete this.offset;delete this.dim;return a},render:function(){var a=this,b=a.options.postView;DISQUS.log("Model:",a.model.id);a.options.count===0?(a.$el.hide(),b.trackPosition=!1):(b.trackPosition=!0,a.$el.html(DISQUS.renderBlock("realtimeReplyNotification",{replies:a.options.count})),a.bindDrain(function(){a.options.thread.queue.drain(a.model.id);
a.setCount(a.options.thread.queue.length);b.trackPosition=!1;a.render()}),a.$el.show(),setTimeout(function(){a.$el.addClass("reveal")},13))}}),w=Backbone.View.extend({render:function(){var a=this.model.usersTyping.count(),b=this.options.parentView.reply;b&&b.isOpen()&&(a-=1);if(a<=0)return void this.$el.hide();a==1?this.$el.html("One other user is typing&hellip;"):this.$el.html(a+" other users are typing&hellip;");this.$el.show()}}),y=l.extend({tagName:"ul",initialize:function(){this.collection.bind("reset",
this.render,this)},render:function(){this.updateDom(function(){var a=this;a.$el.empty();a.collection.length?a.collection.each(function(b){b=DISQUS.renderBlock("notification",{rawHtmlContent:b.get("formatted").text,timeAgo:moment(b.get("timestamp")).fromNow()});a.$el.append($(b))}):a.$el.text("You have no new notifications.");this.trigger("render")},this);return this}}),s=l.extend({tagName:"ul",className:"loading",initialize:function(a){this.collection.bind("reset",this.render,this);this.session=a.session},
render:function(){this.updateDom(function(){this.$el.removeClass("loading");this.$el.empty();this.collection.each(function(a){this.$el.append(DISQUS.renderBlock("activityItem",{activity:a.toJSON(),session:this.session?this.session.toJSON():null}))},this);this.trigger("render")},this);return this}}),G=Backbone.View.extend({initialize:function(a){var b=this;b.notifications=new y({collection:a.notifications});b.activity=new s({collection:new e.PostActivityCollection,session:f.session});Backbone.when([b.notifications,
"render"],[b.activity,"render"]).then(function(){b.isRendered=!0;b.trigger("render:all")});b.render();b.fetched=!1},render:function(){this.$el.html(DISQUS.renderBlock("dashboard"));this.$el.find("[data-role=notifications]").append(this.notifications.el).show();this.$el.find("[data-role=activity]").append(this.activity.el).show()},show:function(){if(!this.fetched)this.activity.collection.fetch(),this.fetched=!0,this.notifications.collection.markRead()}}),I=l.extend({tagName:"ol",className:"loading",
initialize:function(){this.collection.bind("reset",function(){this.updateDom(this.render,this)},this)},render:function(){this.updateDom(function(){this.$el.removeClass("loading");this.$el.empty();this.collection.each(function(a){var b=DISQUS.assureOffset(a.get("createdAt"));this.$el.append(DISQUS.renderBlock("topThread",{id:a.id,title:a.get("title"),url:a.get("link"),numPosts:a.get("postsInInterval"),numLikes:a.get("likes"),timeAgo:moment(b,DISQUS.ISO_8601).fromNow()}))},this);this.trigger("render")},
this);this.attachPosts();return this},attachPosts:function(){this.collection.each(function(a){this.renderPost(a)},this)},renderPost:function(a){var b=a.get("topPost");if(b){var d=_.strip(b.message),d=_.truncate(d,160,"&hellip;"),e=DISQUS.renderBlock("topThreadPost",{message:d,author:b.author});this.updateDom(function(){this.$el.find("[data-role=thread-"+a.id+"] [data-role=top-thread-post]").html(e)},this)}}}),H=l.extend({tagName:"ol",className:"loading",initialize:function(){this.collection.bind("reset",
function(){this.updateDom(this.render,this)},this)},render:function(){this.updateDom(function(){this.$el.removeClass("loading");this.$el.empty();this.collection.each(function(a){this.$el.append(DISQUS.renderBlock("topUser",{user:a.toJSON()}))},this);this.trigger("render")},this);return this}}),J=Backbone.View.extend({initialize:function(a){var b=this;b.forum=a.forum;b.topThreads=new I({id:"top-threads",collection:new e.TopThreadCollection(null,{forum:b.forum.id,limit:10})});b.topUsers=new H({id:"top-users",
collection:new e.TopUserCollection(null,{forum:b.forum.id,limit:20})});Backbone.when([b.topUsers,"render"],[b.topThreads,"render"]).then(function(){b.isRendered=!0;b.trigger("render:all")});b.fetched=!1;b.render()},render:function(){this.$el.html(DISQUS.renderBlock("community",{forum:this.forum.toJSON()}));this.$el.find("[data-role=top-threads]").append(this.topThreads.el);this.$el.find("[data-role=top-users]").append(this.topUsers.el);return this},show:function(){if(!this.fetched)this.topThreads.collection.fetch(),
this.topUsers.collection.fetch(),this.fetched=!0}}),S=l.extend({initialize:function(a){this.$el.addClass("loading");this.thread=a.thread;this.session=a.session;this.collection.on("add reset",this.render,this)},render:function(a,b,d){var e=this,f=(d&&d.index!=null?[e.collection.at(d.index)]:e.collection).map(function(a){a=new M({model:a,thread:e.thread,session:e.session});a.render();return a.el});e.updateDom(function(){e.$el.removeClass("loading");e.$el.append(f);e.isRendered=!0;e.trigger("render:all")})},
show:function(){this.collection.length>0||this.collection.fetch()}}),q={toggleFollow:function(a){a.preventDefault();this.user.get("isFollowing")?(this.user.unfollow(),$(a.target).removeClass("active")):($(a.target).addClass("active"),this.user.follow())}},F=Backbone.View.extend({events:{"click [data-action=close]":"close","click [data-action=toggleFollow]":"toggleFollow"},initialize:function(a){var b=this;b.user=a.user;b.session=a.session;b.user.get("numFollowers")===null&&b.user.fetch({success:function(){b.updateStats()}});
b.user.on("change",b.updateStats,b);b.user.on("change:connections",b.updateConnections,b);b.user.on("change:isFollowing",b.updateActions,b);b.activity=new s({id:"activity",collection:new e.ActivityCollection(null,{user:b.user,include:"user"}),session:b.session});b.activity.on("render",function(){b.isRendered=!0;b.trigger("render:all")});b.render()},updateStats:function(){this.$el.find("[data-role=profile-stats]").html(DISQUS.renderBlock("profileStats",{user:this.user.toJSON()}))},updateActions:function(){this.$el.find("[data-role=actions]").html(DISQUS.renderBlock("profileActions",
{user:this.user.toJSON(),sessionId:this.session.id}))},updateConnections:function(){DISQUS.blocks.profileConnections&&this.$el.find("[data-role=connections]").html(DISQUS.renderBlock("profileConnections",{user:this.user.toJSON()}))},close:function(){this.trigger("close")},render:function(){this.$el.empty();this.$el.append(DISQUS.renderBlock("profile",{user:_.extend(this.user.toJSON(),{isModerator:f.thread.isModerator(this.user)}),sessionId:this.session.id}));this.$el.find("[data-role=activity]").append(this.activity.el)},
show:function(){this.activity.collection.fetch()}});_.extend(F.prototype,q);var x=l.extend({events:{"click [data-action=toggleFollow]":"toggleFollow"},initialize:function(a){var b=this;b.session=a.session;b.user=a.user;b.hoverState="out";b.user.on("change:numPosts change:numLikesReceived",_.debounce(function(){b.updateCounters()}));b.user.on("change:isFollowing",function(){b.updateActions()});b.session.on("change:id",function(){b.render()});b.render();$(document).bind("mouseout",_.debounce(function(a){a=
a.relatedTarget||a.toElement;(!a||a.nodeName==="HTML")&&b.leave()}),10);b.enterTimeout=null;b.leaveTimeout=null;b.$target=null;x.instances[b.user.id]=b},render:function(){var a=this,b=a.user.toJSON();if(b.about)b.about=_.truncate(b.about,80,"...");b.isModerator=f.thread.isModerator(a.user);this.setElement($(DISQUS.renderBlock("hovercard",{user:b,sessionId:a.session.id})));a.$el.bind("mouseover",function(){a.enter()});a.$el.bind("mouseout",function(){a.leave()})},updateCounters:function(){var a=this.$el.find("[data-role=counters]");
this.updateDom(function(){a.html(DISQUS.renderBlock("hovercardCounters",{user:this.user.toJSON(),sessionId:this.session.id}))},this)},updateActions:function(){var a=this.$el.find("[data-role=actions]");this.updateDom(function(){a.html(DISQUS.renderBlock("hovercardActions",{user:this.user.toJSON(),sessionId:this.session.id}))},this)},enter:function(a){var b=this;if(a)this.$target=a;b.leaveTimeout&&clearTimeout(b.leaveTimeout);if(b.hoverState!=="in")b.hoverState="in",b.enterTimeout=setTimeout(function(){b.hoverState===
"in"&&b.show();b.enterTimeout=null},x.DELAY_ENTER)},leave:function(){var a=this;a.enterTimeout&&clearTimeout(a.enterTimeout);if(a.hoverState!=="out")a.hoverState="out",a.leaveTimeout=setTimeout(function(){a.hoverState==="out"&&a.hide();a.leaveTimeout=null},x.DELAY_LEAVE)},show:function(){this.user.get("numLikesReceived")===null&&this.user.fetch();this.$target.append(this.el)},hide:function(){this.$el.remove()}},{DELAY_ENTER:350,DELAY_LEAVE:175,instances:{},create:function(a){var b=a.targetElement,
d=a.user,e=x.instances[d.id]||new x({user:d,session:a.session});b.bind("mouseover",function(){e.enter(b)});b.bind("mouseout",function(){e.leave()});return e}});_.extend(x.prototype,q);var M=l.extend({events:{"click [data-action=remove]":"destroyReaction"},initialize:function(a){this.thread=a.thread;this.session=a.session;this.session.on("change:thread",this.renderMenu,this)},render:function(){this.setElement($(DISQUS.renderBlock("reaction",{reaction:this.model.toJSON(),thread:this.thread.toJSON()})))},
renderMenu:function(){var a=this.$el.find("[data-role=menu]"),b=DISQUS.renderBlock("reactionMenu",{thread:this.session.get("thread")});this.updateDom(function(){a.html(b)},this)},destroyReaction:function(a){a&&a.preventDefault&&a.preventDefault();this.model.destroy();this.updateDom(function(){this.remove()},this)}}),E=l.extend({events:{"click [data-action=dismiss]":"dismiss"},initialize:function(a){this.message=a.message;this.type=a.type},render:function(){this.setElement($(DISQUS.renderBlock("alert",
{message:this.message,type:this.type})));return this},dismiss:function(a){a&&a.preventDefault&&a.preventDefault();this.remove()}}),L=l.extend({events:{"click [data-action=cancel]":"cancel"},initialize:function(){var a=this;a.loading=!1;if(!a.model.get("ipAddress"))a.loading=!0,a.model.on("change:ipAddress",function z(){a.model.off("change:ipAddress",z);a.loading=!1;a.redraw()}),a.model.fetch()},render:function(){var a=this;a.setElement($(DISQUS.renderBlock("blacklist",{loading:this.loading,post:a.model.toJSON()})));
a.$el.bind("submit",function(b){b&&b.preventDefault()&&b.preventDefault();a.submit()});return a},redraw:function(){var a=this.el.parentNode;a&&(this.render(),this.updateDom(function(){$(a).empty().append(this.el)},this))},cancel:function(a){a&&a.preventDefault()&&a.preventDefault();this.trigger("cancel")},submit:function(){var a={},b=this;b.$el.find("input").each(function(){if(this.checked)a[this.name]=this.value});if(!_.isEmpty(a))a.forum=b.model.get("forum"),DISQUS.api.call("blacklists/add.json",
{method:"POST",data:a,success:function(){b.trigger("success")}})}}),D=l.extend({events:{keyup:"handleKeychange",paste:"handleKeychange"},render:function(){var a=this;a.$el.autoresize({maxHeight:350});a.$el.bind("resize",_.throttle(function(){_.delay(_.bind(a.updateDom,a),200)},500));return a},resize:function(){this.$el.trigger("paste")},get:function(){return this.$el.val()},set:function(a){this.$el.val(a)},clear:function(){this.set("")},focus:function(){this.el.focus()},handleKeychange:function(){this.trigger("keychange")}}),
B=D.extend({initialize:function(a){a=a||{};this.thread=a.thread;this.mentionsCache=new e.UserCollection;this.suggestions=new N({thread:a.thread,mentions:this.mentionsCache});this.placeholder="";this.suggestions.on("select",this.insertMention,this);this.reset()},reset:function(){this.searchTerms=this.anchorOffset=this.anchorNode=null;this.suggestions.clear()},render:function(){var a=this.el.placeholder,b=document.createElement("div");_.extend(b,{className:"textarea",contentEditable:!0,innerHTML:this.el.value});
var d=this.el.parentNode;d.replaceChild(b,this.el);this.setElement(b);this.bindKeyEvents();d.appendChild(this.suggestions.el);this.content=new Editable(this.el);D.prototype.render.call(this);if(a)this.placeholder='<span class="placeholder">'+a+"</span>",this.$el.html()||this.$el.html(this.placeholder),this.$el.bind("focus",_.bind(function(){this.isPlaceholder()&&this.$el.empty()},this)),this.$el.bind("blur",_.bind(function(){this.content.text()===""&&this.$el.html(this.placeholder)},this));return this},
isPlaceholder:function(){return this.$el.find(".placeholder").length!==0},bindKeyEvents:function(){this.$el.bind("keydown",_.bind(function(a){switch(a.keyCode){case 9:this.suggestions.active&&(this.suggestions.select(),a.preventDefault(),a.stopPropagation());break;case 10:case 13:case 38:case 40:this.suggestions.active&&(a.preventDefault(),a.stopPropagation())}},this));var a=_.throttle(_.bind(this.suggest,this),500);this.$el.bind("keyup",_.bind(function(b){b.preventDefault();b.stopPropagation();this.checkExistingMentions();
switch(b.keyCode){case 50:if(!b.shiftKey)break;this.start(b);break;case 10:case 13:this.suggestions.select();break;case 27:this.reset(b);break;case 38:this.suggestions.move("up");break;case 40:this.suggestions.move("down");break;default:a(b)}},this))},start:function(){this.reset();this.suggest()},suggest:function(){this.suggestions.suggest(this.parseSearchTerms())},insertMention:function(a){var b=this.thread.users.getByCid(a);this.selectSearchString(b);this.mentionsCache.getByCid(a)||this.mentionsCache.add(b);
this.content.insertHTML(B.getMentionHtml(b));a=this.$el.find("span[data-cid]");_.each(a,function(a){if(a.contentEditable!==!1)a.contentEditable=!1})},selectSearchString:function(a){a.get("name").toLowerCase();this.content.selectNodeText(this.anchorNode,this.anchorOffset-1,this.anchorOffset+Editable.normalizeSpace(this.anchorNode.nodeValue.slice(this.anchorOffset)).toLowerCase().length)},get:function(){var a=this,b=B.isMention;_.toArray(this.el.childNodes);if(this.isPlaceholder())return"";return this.content.text(function(d){return b(d,
!0)?a.mentionToText(d):null})},set:function(a){this.el.innerHTML=a},parseSearchTerms:function(){var a=this.content.selectedTextNode(),b=a?a.nodeValue:"",d=Editable.normalizeSpace;if(b){var e=this.content.selectedTextNodeOffset(a),f=Editable.normalizeSpace(b.slice(0,e).split("").reverse().join("")).indexOf("@");if(f===-1)return null;this.anchorNode=a;this.anchorOffset=e-f;if(a=d(b.slice(this.anchorOffset-1,e)).match(B.MENTIONS_RE))return a[0].slice(1).split(" ");if(f===0)return[""]}},checkExistingMentions:function(){var a=
Editable.normalizeSpace,b=this.$el.find("span"),b=_.filter(b,B.isMention),d=this.mentionsCache,e={};_.each(b,function(b){var f=$(b).attr("data-cid"),g=_.reduce(this.content.getTextNodes(b),function(b,d){return b+a(d.nodeValue)},""),h=d.getByCid(f);h.get("name")!==g?(this.mentionsCache.remove(h),this.content.removeNode(b),this.content.insertHTML(" "),this.reset()):e[f]=b},this);d.each(function(a){e[a.cid]||d.remove(a)})},mentionToText:function(a){a=this.mentionsCache.getByCid($(a).attr("data-cid"));
return["@",a.get("username")||a.get("emailHash"),":disqus"].join("")}},{MENTIONS_RE:/@\w+\s?(?:\w+\s?){0,5}(?:\w+)?$/,isMention:function(a,b){var d;do{d=$(a);if(d.hasClass("mention")&&d.attr("data-cid"))return!0;a=a.parentElement}while(b&&a);return!1},getMentionHtml:function(a){return'<span contenteditable="true"><span contenteditable="false" data-cid="'+a.cid+'" class="mention">'+a.get("name")+"</span></span>&nbsp;"}}),N=Backbone.View.extend({events:{"click li":"onclick"},initialize:function(a){this.active=
!1;this.thread=a.thread;this.mentionsCache=a.mentions},suggest:function(a){a=this.findMatches(a);if(!a||!a.length)return void this.clear();this.active=!0;this.el.innerHTML=DISQUS.renderBlock("suggestions",{users:_.map(a,function(a){return _.extend(a.toJSON(),{cid:a.cid})})});this.$el.find("li[data-cid]").first().addClass("active")},clear:function(){this.active=!1;this.el.innerHTML=""},onclick:function(a){this.select($(a.currentTarget).attr("data-cid"))},findMatches:function(a){if(a&&a.length){for(var b=
RegExp(a.join(" ").replace(/[^\w\s]/,""),"i"),d=N.MAX_SUGGESTIONS,e=this.thread.users,f=[],h=0,i,a=a.length===1&&a[0]===""?function(){return!0}:function(a){return b.test(a.get("name"))||b.test(i.get("username"))},h=0;h<e.models.length&&f.length<d;h++)i=e.models[h],this.mentionsCache.getByCid(i.cid)||a(i)&&f.push(i);return f}},select:function(a){this.active&&(a||(a=this.$el.find(".active").attr("data-cid")),this.trigger("select",a),this.clear())},move:function(a){if(this.active){var b=this.$el.find(".active"),
a=b[a==="up"?"previous":"next"]();a.length&&a.attr("data-cid")&&(b.removeClass("active"),a.addClass("active"))}}},{MAX_SUGGESTIONS:5}),R=l.extend({tagName:"ul",initialize:function(a){_.extend(this,a)},render:function(){var a={};a.Shortname=this.thread.get("forum");a["Thread ID"]=this.thread.get("id");a["Thread slug"]=this.thread.get("slug");this.$el.empty();_.each(a,function(a,b){var c=document.createElement("li");c.innerHTML="<strong>"+b+"</strong>: "+a;this.$el.append(c)},this);return this}}),K=
Backbone.View.extend({events:{"click [data-nav]":"_navTo"},initialize:function(){this.prevDestination=this.activeNav()},_navTo:function(a){a.preventDefault();a=$(a.target);a=a.is("[data-nav]")?a:a.closest("[data-nav]");a=a.attr("data-nav");if(this.prevDestination==a)return!1;this.navTo(a)},navTo:function(a){this.prevDestination=a;var b=this.$el.find("[data-nav="+a+"]").parent();b.siblings("li").removeClass("active");b.addClass("active");this.trigger("nav",a)},activeNav:function(){if(this.prevDestination!=
null)return this.prevDestination;return this.$el.find(".active [data-nav]").attr("data-nav")},clear:function(){this.$el.find("li").removeClass("active");this.prevDestination=null}});return{Lounge:k,LoungeSubView:l,PostView:r,PostReplyView:o,PostEditView:n,ReactionView:M,QueuedPostView:A,QueuedReplyView:v,TypingUserView:w,CommunityView:J,TopThreadCollectionView:I,TopUserCollectionView:H,DashboardView:G,NotificationCollectionView:y,NotificationCountView:p,ActivityCollectionView:s,ProfileView:F,HoverCard:x,
CaptchaView:u,AlertView:E,BlacklistView:L,ContentEditableView:B}});DISQUS.define("ga",function(b){var e,d=function(a){e?e(a):b._gaq.push(a)},i={component:1,"package":2,forum:3,version:4,userType:5};return{setCaller:function(a){e=a},setAccount:function(a){d(["_setAccount",a])},setCustomVar:function(a,b){d(["_setCustomVar",i[a],a,b])},trackPageview:function(){d(["_trackPageview"])},trackEvent:function(a,b,e){d(["_trackEvent",b,a,e,1])},setDomainName:function(a){d(["_setDomainName",a])}}});
DISQUS.define("juggler",function(b){var e,d,i={},a=["thread","forum","forum_id"],j=a.slice().concat(["imp","event"]),f=[],h=(new Date).getTime().toString(10)+Math.floor(Math.random()*1E6).toString(10);return{load:function(j){b.location.href.slice(0,5)=="https"?e=function(){}:(DISQUS.cookies.create("__jid",h,{expiresIn:18E5}),d=j.url,DISQUS.each(a,function(a){i[a]=j[a]}),i.imp=h,e=function(a){DISQUS.each(i,function(b,d){a[d]=i[d]});DISQUS.require(d,a,!1)},DISQUS.each(f,function(a){e(a)}))},emit:function(a,
b){DISQUS.each(j,function(a){if(b[a]!=null)throw"Error: cannot overwrite event context '"+a+"'";});b.event=a;e==null?f.push(b):e(b)},impId:h}});
DISQUS.define("intelligence",function(b){function e(b,e){function a(a){if(!(a instanceof DISQUS.lounge.models.User))throw Error("determineUserType(user) needs an instance of User");return a.has("remote")?a.get("remote").domain:a.id?"disqus":r?"guest":"not_logged_in"}function j(a){if(e.switches.length>0)a(e.switches);else e.switches.on("reset",a)}var f;f="https:"==b.document.location.protocol?"https://ssl":"http://www";if(!DISQUS.debug){DISQUS.require(f+".google-analytics.com/ga.js",{});b._gaq=b._gaq||
[];var h=DISQUS.ga.setCustomVar,q=DISQUS.ga.trackPageview,k=function(a){DISQUS.ga.trackEvent(a,m,o)};DISQUS.ga.setAccount("UA-1410476-6");DISQUS.debug||DISQUS.ga.setDomainName(".disqus.com");var l=e.initialData,m="next",o=l.forum.id,n="not_logged_in",r=!1,u=l.features.support_preferred?"plus":l.features.support_priority?"pro":l.features.support_vip?"vip":"free";e.session.on("identify",function(){var f=this;j(function(a){a.enabled("juggler_thread_onReady")&&DISQUS.juggler.emit("init_embed",{thread_slug:l.thread.slug,
user_type:f.get("user_type")||"anon",referrer:b.document.referrer,theme:"next",prev_imp:DISQUS.cookies.read("__jid")})});n=a(f);h("component","embed");h("package",u);h("forum",o);h("version",m);h("userType",n);q();e.session.on("change:id",function(b){var d=n;n=a(b);d!=n&&(h("userType",n),k(n=="not_logged_in"||n=="guest"?"logout":"login"))})});j(function(a){a.enabled("juggler_enabled")&&DISQUS.juggler.load({url:"http://juggler.services.disqus.com/event.js",thread:l.thread.id,forum:l.forum.id,forum_id:l.forum.pk})});
e.on("inViewport",function(){k("view_embed");e.off("inViewport")});e.on("uiAction:createPost",function(){n=="not_logged_in"&&(n="guest",h("userType",n));r=!0;k("post_comment")});e.on("uiAction:postUpvote",function(){k("like_comment")});e.on("uiAction:postDownvote",function(){k("dislike_comment")});e.on("uiAction:threadUpvote",function(){k("like_thread")});e.on("uiAction:postShare",function(a){k("share_comment_"+a)})}}return{init:function(d){e(b,d)}}});
(function(){DISQUS.log=function(){var b=DISQUS.lounge.views.Lounge.getInstance();window.console&&Function.prototype.bind&&b&&b.switches&&b.switches.enabled("next_logging")&&Function.prototype.bind.call(window.console.log,window.console).apply(window.console,Array.prototype.slice.call(arguments,0))};$(document).ready(function(){function b(){$(".dropdown").removeClass("open")}$("html").bind("click",b);$("body").delegate("[data-toggle]","click",function(e){e.stopPropagation();e.preventDefault();var e=
$(e.currentTarget),e=e.closest("."+e.attr("data-toggle")),d=e.attr("data-dropdown")!="disabled"&&!e.hasClass("open");e.attr("data-dropdown","enabled");b();d&&e.addClass("open")});DISQUS.Bus.bind("window.click",b)})})();