var DISQUS=function(d){var c={AssertionError:function(a){this.message=a}};c.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};c.assert=function(a,b){if(!a)throw new c.AssertionError(b);};var b=[];c.define=function(a,e){typeof a==="function"&&(e=a,a="");for(var g=a.split("."),h=g.shift(),f=c,l=(e||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},d);h;)f=f[h]?f[h]:f[h]={},h=g.shift();for(var i in l)l.hasOwnProperty(i)&&
(l.__overwrites__||f[i]!==null&&c.assert(!f.hasOwnProperty(i),"Unsafe attempt to redefine existing module with "+i),f[i]=l[i],b.push(function(a,b){return function(){delete a[b]}}(f,i)));return f};c.use=function(a){return c.define(a)};c.cleanup=function(){for(var a=0;a<b.length;a++)b[a]()};return c}(this);
DISQUS.define(function(d,c){var b=d.document,a=b.getElementsByTagName("head")[0]||b.body,e={running:!1,timer:null,queue:[]};DISQUS.defer=function(a,b){function f(){var a=e.queue;if(a.length===0)e.running=!1,clearInterval(e.timer);for(var b=0,g;g=a[b];b++)g[0]()&&(a.splice(b--,1),g[1]())}e.queue.push([a,b]);f();if(!e.running)e.running=!0,e.timer=setInterval(f,100)};DISQUS.each=function(a,b){var f=a.length,e=Array.prototype.forEach;if(isNaN(f))for(var c in a)a.hasOwnProperty(c)&&b(a[c],c,a);else if(e)e.call(a,
b);else for(e=0;e<f;e++)b(a[e],e,a)};DISQUS.serializeArgs=function(a){var b=[];DISQUS.each(a,function(a,g){a!==c&&b.push(g+(a!==null?"="+encodeURIComponent(a):""))});return b.join("&")};DISQUS.serialize=function(a,b,f){b&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=DISQUS.serializeArgs(b));if(f)return b={},b[(new Date).getTime()]=null,DISQUS.serialize(a,b);b=a.length;return a.charAt(b-1)=="&"?a.slice(0,b-1):a};DISQUS.require=function(e,h,f,c,d){function n(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))c&&
c(),m&&clearTimeout(m),DISQUS.bean.remove(a.target,p,n)}var j=b.createElement("script"),p=j.addEventListener?"load":"readystatechange",m=null;j.src=DISQUS.serialize(e,h,f);j.async=!0;j.charset="UTF-8";(c||d)&&DISQUS.bean.add(j,p,n);d&&(m=setTimeout(function(){d()},2E4));a.appendChild(j);return DISQUS};DISQUS.requireStylesheet=function(e,h,f){var c=b.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=DISQUS.serialize(e,h,f);a.appendChild(c);return DISQUS};DISQUS.requireSet=function(a,
b,e){var c=a.length;DISQUS.each(a,function(a){DISQUS.require(a,{},b,function(){--c===0&&e()})})};DISQUS.injectCss=function(e){var c=b.createElement("style");c.setAttribute("type","text/css");e=e.replace(/\}/g,"}\n");d.location.href.match(/^https/)&&(e=e.replace(/http:\/\//g,"https://"));c.styleSheet?c.styleSheet.cssText=e:c.appendChild(b.createTextNode(e));a.appendChild(c)}});
DISQUS.define("JSON",function(){function d(a){return a<10?"0"+a:a}function c(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=i[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(a,h){var d,g,j,i,m=f,o,k=h[a];k&&typeof k==="object"&&typeof k.toJSON==="function"&&!e&&(k=k.toJSON(a));typeof n==="function"&&(k=n.call(h,a,k));switch(typeof k){case "string":return c(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);
case "object":if(!k)return"null";f+=l;o=[];if(Object.prototype.toString.apply(k)==="[object Array]"){i=k.length;for(d=0;d<i;d+=1)o[d]=b(d,k)||"null";j=o.length===0?"[]":f?"[\n"+f+o.join(",\n"+f)+"\n"+m+"]":"["+o.join(",")+"]";f=m;return j}if(n&&typeof n==="object"){i=n.length;for(d=0;d<i;d+=1)g=n[d],typeof g==="string"&&(j=b(g,k))&&o.push(c(g)+(f?": ":":")+j)}else for(g in k)Object.hasOwnProperty.call(k,g)&&(j=b(g,k))&&o.push(c(g)+(f?": ":":")+j);j=o.length===0?"{}":f?"{\n"+f+o.join(",\n"+f)+"\n"+
m+"}":"{"+o.join(",")+"}";f=m;return j}}var a={},e=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,l,i={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;a.stringify=function(a,e,c){var d;l=f="";if(typeof c==="number")for(d=0;d<c;d+=1)l+=" ";else typeof c==="string"&&(l=c);if((n=e)&&typeof e!=="function"&&(typeof e!=="object"||typeof e.length!=="number"))throw Error("JSON.stringify");return b("",{"":a})};a.parse=function(a,b){function e(a,
c){var f,d,g=a[c];if(g&&typeof g==="object")for(f in g)Object.hasOwnProperty.call(g,f)&&(d=e(g,f),d!==void 0?g[f]=d:delete g[f]);return b.call(a,c,g)}var c,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return c=eval("("+a+")"),
typeof b==="function"?e({"":c},""):c;throw new SyntaxError("JSON.parse");};var j={a:[1,2,3]},p,m;if(Object.toJSON&&Object.toJSON(j).replace(/\s/g,"")==='{"a":[1,2,3]}')p=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(j='{"a":[1,2,3]}'.evalJSON(),j.a&&j.a.length===3&&j.a[2]===3&&(m=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),e=!(a&&a.length===3&&a[2]===3))})();if(e||!p||!m)return{stringify:a.stringify,parse:a.parse};return{stringify:p,
parse:m}});
DISQUS.define("Bus",function(){function d(a){a=a.split("/");return a[0]+"//"+a[2]}var c=DISQUS.use("JSON"),b=window.location.hash.slice(1),a=window.parent,e=document.referrer,g={};g.client=d(document.location.href);g.host=e?d(e):g.client;return{origins:g,postMessage:function(e){e.sender=b;e=c.stringify(e);a.postMessage(e,g.host)},sendHostMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:b})},sendGlobalMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:b})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var d=window.addEventListener?window.addEventListener:window.attachEvent,c=window.addEventListener?"message":"onmessage";if(!d)throw Error("No event support.");d(c,function(b){var a=DISQUS.Bus,e=b.origin;if(!(e!=a.origins.client&&e!=a.origins.host)){var c;try{c=DISQUS.JSON.parse(b.data)}catch(d){return}b=c.data;switch(c.scope){case "client":a.trigger(b.eventName,b.data)}}},!1)});
DISQUS.define(function(d){var d=d.document,c=require("bean"),b=_.extend,a=navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i),e;try{localStorage.setItem("_test","_test"),localStorage.removeItem("_test"),e=!0}catch(g){e=!1}var h={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:c,extend:b,debug:!1,browser:{mobile:a,localStorage:e,contentEditable:"isContentEditable"in d.documentElement},addBlocks:function(){return function(a){a(DISQUS)}}};
h.templateGlobals={urls:DISQUS.use("urls"),sso:null,_:{pluralize:_.pluralize}};h.renderBlock=function(a,b){return DISQUS.blocks[a](h.templateGlobals,b)};h.assureOffset=function(a){return a.indexOf("+")>=0?a:a+"+00:00"};e=h.Builder=function(){this.accum=[]};_.extend(e.prototype,{put:function(a){this.accum.push(a)},esc:function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});
return h});
DISQUS.define("urls",function(){return{media:"http://mediacdn.disqus.com/1339189988",root:"http://disqus.com",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+encodeURIComponent(document.referrer),help:"http://disqus.com/help/",editProfile:"http://disqus.com/account/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",
facebook:"http://disqus.com/_ax/facebook/begin/"},loading:"http://mediacdn.disqus.com/1339189988/html/simple-loading.html",avatar:{generic:"http://mediacdn.disqus.com/1339189988/images/noavatar92.png"}}});
DISQUS.define("api",function(){function d(a){function b(d){var h=d.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,h.length)===h&&(d=DISQUS.JSON.parse(d.originalEvent.data),d.requestId==c&&(h=d.code===0?a.success:a.error,delete d.requestId,(h||function(){})(d),document.body.removeChild(i),document.body.removeChild(f),$(window).unbind("message",b)))}var c=_.uniqueId(),d=document.createElement("div"),f=document.createElement("form"),l="frame_"+c,i;d.innerHTML='<iframe name="'+l+'"></iframe>';i=d.childNodes[0];
f.target=l;f.action=a.url.replace(".json",".pm");f.method=a.method||"GET";a.data=_.extend(a.data,{callback:c,referrer:document.referrer});_.each(a.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var e=document.createElement("input");e.type="hidden";e.name=b;e.value=a;f.appendChild(e)})});$(window).bind("message",b);document.body.appendChild(i);document.body.appendChild(f);f.submit()}function c(a){a=_.defaults(a,b);a.data=a.data||{};a.data.api_key=
DISQUS.apiKey;$.ajax(a)}var b={};return{defaults:function(a){_.extend(b,a)},ajax:c,call:function(a,b){b=b||{};b.url=(b.secure?DISQUS.urls.apiSecure:DISQUS.urls.api)+a;b.data=_.extend(b.data||{},{api_key:DISQUS.apiKey});(b.secure?d:c)(b)}}});(function(d){d.ajax=function(c){c.method=c.type;c.type=c.dataType;delete c.dataType;return DISQUS.api.ajax(c)};d.Collection.prototype.parse=function(c){return c.response}})(Backbone);
DISQUS.define("discovery.models",function(){var d=Backbone.Model.extend({defaults:{author:null,category:null,createdAt:null,forum:null,identifiers:[],ipAddress:null,isClosed:!1,isDeleted:!1,link:null,message:null,slug:null,title:null,userSubscription:!1,posts:0,reactions:0,likes:0,dislikes:0,userScore:0},url:DISQUS.urls.api+"threads/details",parse:function(b){return b.response}}),c=d.extend({defaults:_.extend({},d.prototype.defaults,{redirectUrl:null})});return{Thread:d,RelatedThread:c}});
DISQUS.define("discovery.collections",function(d){var c=function(){if(!d.console||!Function.prototype.bind)return function(){};var a=Function.prototype.bind.call(d.console.log,d.console);return function(){a.apply(d.console,arguments)}}(),b=DISQUS.use("discovery.models");return{RelatedThreadCollection:Backbone.Collection.extend({model:b.RelatedThread,url:function(){return!DISQUS.debug?DISQUS.urls.api+"discovery/listRelated.json":DISQUS.urls.api+"threads/list.json"},initialize:function(a,b){this.mainThread=
b.thread;this.limit=b.limit;this.legacyMode=b.legacyMode;this.impId=(new Date).getTime().toString(10)+Math.floor(Math.random()*1E6).toString(10)},fetch:function(a){var b={};b.data=!DISQUS.debug?{thread:this.mainThread.get("id")}:{forum:this.mainThread.get("forum").id};b.parse=!1;if(!DISQUS.debug&&this.legacyMode)b.data.legacyMode=1,b.data.limit=this.limit;_.extend(b,a);Backbone.Collection.prototype.fetch.call(this,b)},parse:function(a){var b=[],d=a.response;c("Results (",d.length,"):",d);for(var h=
0,f=d.length;h<f&&b.length<this.limit;h++)if(a=d[h].thread||d[h],a.id!=this.mainThread.id)a.posts===0?c("Thread",a.id,"does not have any comments."):a.title.indexOf("http://")===0?c("Thread",a.id,"has a title that starts with http."):(a.redirectUrl=d[h].signedUrl?DISQUS.serialize("http://redirect.disqus.com/url",{url:d[h].signedUrl,thread:a.id,forum:a.forum,zone:"discovery",imp:this.impId,source_thread_id:this.mainThread.id}):a.link+"#redirect",a.score={score:d[h].score,k:d[h].k},b.push(a));c("Total results:",
b.length);return b}})}});
DISQUS.define("discovery.views",function(){var d=Backbone.View.extend({events:{"click [data-action=discovery-close]":"close","click [data-action=discovery-help]":"showHelp"},dtplBlock:"relatedThreads",initialize:function(b){this.snippetLimit=b.snippetLimit;this.legacyMode=b.legacyMode},close:function(b){b.preventDefault();this.remove();this.trigger("resize",0)},showHelp:function(b){b.preventDefault();$(b.currentTarget).hide();this.$el.find("#discovery-note").show();this.trigger("resize")},render:function(){if(this.collection.length<
2)return this;this.setElement(DISQUS.renderBlock(this.dtplBlock,{forum:this.collection.mainThread.get("forum")}));this.collection.legacyMode&&this.$el.find("#discovery-options").prepend($("<span/>").text("LEGACY"));var b=_.after(this.collection.length,_.bind(function(){this.trigger("allSubviewsRendered")},this));this.collection.each(function(a){a=new c({model:a,snippetLimit:this.snippetLimit});a.render();this.$el.find("section > ul").append(a.el);a.on("topCommentRendered",b)},this);return this}}),
c=Backbone.View.extend({events:{"click [data-redirect]":"swapLink"},dtplBlock:"relatedThread",initialize:function(b){this.snippetLimit=b.snippetLimit},swapLink:function(b){b=b.target||b.srcElement;b.tagName.toUpperCase()=="A"&&b.getAttribute("data-redirect")||(b=$(b).closest("a[data-redirect]")[0]);var a=b;a.setAttribute("data-href",a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",a.getAttribute("data-href"))},100)},getTopComment:function(b){var a=
this,d=!DISQUS.debug?"posts/listPopular.json":"posts/list.json",c={forum:":all",thread:a.model.get("id"),limit:1};if(!DISQUS.debug)c.order="best",c.interval="60d",c.nonDefaultAvatar=1;DISQUS.api.call(d,{method:"GET",data:c,success:function(c){c.response.length!==0&&b.call(a,c.response[0])}});return a},renderAvatar:function(b){var a=this.$el.find("[data-role=discovery-avatar]");a.attr("src",b.avatar.cache);a.attr("alt",this.authorName(b));return this},authorName:function(b){return b.name||b.username},
renderCommentSnippet:function(b){var a=this.$el.find("[data-role=discovery-top-comment]"),c=this.authorName(b.author);a.find("[data-role=discovery-top-comment-author]").text(c);b=_.strip(b.message);b=_.truncate(b,this.snippetLimit);a.find("[data-role=discovery-top-comment-snippet]").text(b);return this},renderTopComment:function(b){this.renderAvatar(b.author);this.renderCommentSnippet(b);this.trigger("topCommentRendered");return this},render:function(){this.setElement(DISQUS.renderBlock(this.dtplBlock,
{thread:this.model.toJSON()}));this.getTopComment(this.renderTopComment);return this}});return{RelatedThreadCollectionView:d,RelatedThreadView:c}});
DISQUS.Bus.bind("init",function(d){function c(b){var c=new l({id:"discovery",collection:b,snippetLimit:e}),d=function(){if(!a)return void DISQUS.Bus.bind("onTemplateAcquired",d);var b=function(a){a=_.isUndefined(a)?$.doc().height:a;DISQUS.Bus.sendHostMessage("resize",{height:a})};c.on("allSubviewsRendered",b);c.on("resize",function(a){b(a)});$("body").append(c.render().$el);b($("#discovery").length&&$("#discovery").height());c.on("allSubviewsRendered",DISQUS.registerActions)};d()}var b=__disqus__theme__,
a=!1;DISQUS.requireStylesheet(b.css,null,DISQUS.debug);DISQUS.require(b.js,null,DISQUS.debug,function(){a=!0;DISQUS.Bus.trigger("onTemplateAcquired")});var e=100,g=DISQUS.use("discovery.models"),b=DISQUS.use("discovery.collections"),h=DISQUS.use("discovery.views"),g=g.Thread,f=b.RelatedThreadCollection,l=h.RelatedThreadCollectionView,i,b=d.identifier?"ident:"+d.identifier:d.slug?"slug:"+d.slug:"link:"+d.url;(new g).fetch({data:{thread:b,forum:d.forum,related:"forum"},success:function(a){i=new f(null,
{thread:a,limit:4,legacyMode:!!d.legacyMode});i.fetch({success:c})}});b=document.createElement("base");b.target="_parent";b.href=d.referrer;$("head").append(b)});DISQUS.Bus.sendHostMessage("ready");