(function(f,h,l){f.SPR||(f.SPR={provide:function(a,b){c[a]||(c[a]=b,"function"===typeof c[a].init&&c[a].init())}});var c=f.SPR;c.provide("Common",{random:function(){return Math.floor(Math.random()*8675309)},isArray:function(a){return Array.isArray?Array.isArray(a):Object.prototype.toString.call(a)==="[object Array]"},isString:function(a){return toString.call(a)=="[object String]"}});c.provide("DOM",{init:function(){c.DOM.on=c.DOM.attachEvent;c.DOM.off=c.DOM.detachEvent},addScript:function(a){var b=
h.createElement("script");b.type="text/javascript";b.setAttribute("async",true);b.src=a;setTimeout(function(){c.DOM.$("HEAD")[0].appendChild(b)},1);return b},onReady:function(a){h.getElementsByTagName("BODY")[0]?a():f.addEventListener?h.addEventListener("DOMContentLoaded",function(){a()},false):function(){if(h.uniqueID||!h.expando){var b=h.createElement("document:ready");try{b.doScroll("left");a()}catch(c){setTimeout(arguments.callee,0)}}}()},attachEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,
c,false):a.attachEvent("on"+b,c);return a},detachEvent:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,false):a.detachEvent("on"+b,c);return a},top:function(a){return a?a.y?a.y:a.offsetTop+c.DOM.top(a.offsetParent):0},left:function(a){return a?a.x?a.x:a.offsetLeft+c.DOM.left(a.offsetParent):0},height:function(a){return Math.max(a.scrollHeight||0,a.offsetHeight||0,a.clientHeight||0)},width:function(a){return Math.max(a.scrollWidth||0,a.offsetWidth||0,a.clientWidth||0)},scroll:function(){var a=
0;return a=f.pageYOffset?f.pageYOffset:h.documentElement?h.documentElement.scrollTop:0},viewport:function(){var a=0,b=0,b=h.documentElement;if(f.innerWidth){a=f.innerWidth;b=f.innerHeight}else{if(!b||!b.clientWidth)b=c.$("BODY")[0];a=b.clientWidth;b=b.clientHeight}return{w:a,h:b}},$:function(a){var b=[],c,i=0,e;if(!a)return[];if(typeof a!=="string")return[a];switch(a.charAt(0)){case "#":b.push(h.getElementById(a.substring(1)));break;case ".":c=h.getElementsByTagName("*");for(e=" "+a.substring(1)+
" ";i<c.length;i=i+1){a=(" "+c[i].className+" ").replace(/[\n\t\r]/g," ");a.indexOf(e)>-1&&b.push(c[i])}break;default:b=h.getElementsByTagName(a)}return b}});c.provide("QS",{escape:function(a){return encodeURIComponent(a)},unescape:function(a){return decodeURIComponent(a)},encode:function(a,b){var d=c.QS,i=[];if(c.Common.isArray(a))for(var e=0,g;e<a.length;e=e+1){g=a[e];/\[\]$/.test(b)?i.push(d.escape(b)+"="+d.escape(g)):i.push(d.encode(g,b+"["+(typeof g==="object"?e:"")+"]"))}else if(typeof a===
"object"&&a!==null&&!("nodeType"in a))for(e in a)Object.prototype.hasOwnProperty.call(a,e)&&(b?i.push(d.encode(a[e],b+"["+e+"]")):i.push(d.encode(a[e],e)));else i.push(d.escape(b)+"="+d.escape(a));return i.join("&")},decode:function(a){for(var b={},d=0,i={"true":true,"false":false,"null":null},a=a.replace(/\+/g," ").split("&");d<a.length;d=d+1){var e=a[d].split("="),g=c.QS.unescape(e[0]),h=b,k=0,j=g.split("]["),f=j.length-1;if(/\[/.test(j[0])&&/\]$/.test(j[f])){j[f]=j[f].replace(/\]$/,"");j=j.shift().split("[").concat(j);
f=j.length-1}else f=0;if(e.length===2){e=(e=c.QS.unescape(e[1]))&&!isNaN(e)?+e:e==="undefined"?void 0:i[e]!==void 0?i[e]:e;if(f)for(;k<=f;k=k+1){g=j[k]===""?h.length:j[k];h=h[g]=k<f?h[g]||(j[k+1]&&isNaN(j[k+1])?{}:[]):e}else c.Common.isArray(b[g])?b[g].push(e):b[g]=b[g]!==void 0?[b[g],e]:e}else g&&(b[g]=void 0)}return b}});c.provide("API",{callbacks:{},jsonp:function(a,b,d,i,e){i=i||l;e||(e="cb");var g="cb"+c.Common.random(),f=c.API;d[e]="SPR.API.callbacks."+g;e=h.location.protocol+"//";e==="file://"&&
(e="http://");var d=c.QS.encode(d),k=c.DOM.addScript(e+a+b+"?"+d);f.callbacks[g]=function(a){setTimeout(function(){k.parentNode.removeChild(k)},0);i(a);try{delete f.callbacks[g]}catch(b){f.callbacks[g]=null}}}});c.provide("de",{api:"feeds.delicious.com",apiPath:"/v2/json/urlinfo/data",collect:function(a){var b=c.de,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"de",data:b})},"callback")}});
c.provide("dg",{api:"services.digg.com",apiPath:"/stories/",collect:function(a){var b=c.dg,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{type:"javascript",link:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"dg",data:b})},"callback")}});c.provide("fb",{api:"graph.facebook.com",apiPath:"/fql",collect:function(a){var b=c.fb,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{q:'SELECT url,total_count,share_count,comment_count,like_count,click_count,commentsbox_count FROM link_stat WHERE url in ("'+
d.url+'")'},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"fb",data:b})},"callback")}});c.provide("gp",{api:"clients6.google.com",apiPath:"rpc",collect:function(){}});c.provide("li",{api:"www.linkedin.com",apiPath:"/countserv/count/share",collect:function(a){var b=c.li,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"li",data:b})},"callback")}});
c.provide("rd",{api:"www.reddit.com",apiPath:"/api/info.json",collect:function(a){var b=c.rd,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"rd",data:b})},"jsonp")}});c.provide("pi",{api:"api.pinterest.com",apiPath:"/v1/urls/count.json",collect:function(a){var b=c.pi,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,
cid:a.id,pid:d.pid,sn:"pi",data:b})},"callback")}});c.provide("su",{api:"www.stumbleupon.com",apiPath:"/services/1.01/badge.getinfo",collect:function(a){var b=c.su,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com","/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"su",data:b})})}});c.provide("tw",{api:"urls.api.twitter.com",apiPath:"/1/urls/count.json",collect:function(a){var b=c.tw,d=c.Reach.config;c.API.jsonp(b.api,b.apiPath,{url:d.url},function(b){c.API.jsonp("cc.simplereach.com",
"/event",{event:"s",url:d.url,cid:a.id,pid:d.pid,sn:"tw",data:b})},"callback")}});c.provide("Reach",{api:"cc.simplereach.com",config:f.__reach_config,init:function(){var a=c.Reach,b=a.config;if(!b||!b.pid||!b.url||!b.date)try{console.log("SPR-ERROR: Please provide pid, url and date in the configuration")}catch(d){}else{if(b.authors)b.authors=a.createList(b.authors);if(b.channels)b.channels=a.createList(b.channels);if(b.tags)b.tags=a.createList(b.tags);if(typeof b.date!=="string")b.date=b.date.toString();
a.config.referrer=h.referrer;c.API.jsonp(a.api,"/n",a.config,function(a){a.de&&c.de.collect(a);a.dg&&c.dg.collect(a);a.fb&&c.fb.collect(a);a.gp&&c.gp.collect(a);a.li&&c.li.collect(a);a.rd&&c.rd.collect(a);a.su&&c.su.collect(a);a.tw&&c.tw.collect(a);a.pi&&c.pi.collect(a)})}},createList:function(a){typeof a==="string"&&(a=a.split(","));if(c.Common.isArray(a)){for(var b=0;b<a.length;b=b+1)a[b]=a[b].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,"");return a.join("|")}}})})(window,document,function(){});
